import React,{useMemo} from 'react';
import {Clock,Target,CheckCircle2,AlertCircle,ArrowRight,Play,RotateCcw,CheckSquare,ShieldCheck,TrendingUp,BookOpen,BarChart3} from 'lucide-react';
import {useApp} from '../../context/AppContext';
import {tZen} from '../../utils/zen';
import {WorkspacePage,MetricRail,Metric,Surface,SectionHeader,PrimaryButton,QuietButton,PageHeader} from '../common/WorkspaceUi';

export const DashboardView:React.FC=()=>{
  const{modules,phases,weekPlans,tasks,mistakes,questions,sessions,setActiveTab,startTimer,toggleTask,zenMode}=useApp();
  const currentWeek=weekPlans[0];const currentPhase=phases.find(p=>p.code===currentWeek?.phase)||phases.find(p=>p.status==='active')||phases[0];const pendingTasks=tasks.filter(t=>t.status==='todo');const pendingMistakes=mistakes.filter(m=>m.status!=='fixed');
  const weekSessions=useMemo(()=>sessions.filter(s=>!currentWeek||(s.date>=currentWeek.startDate&&s.date<=currentWeek.endDate)),[sessions,currentWeek]);const totalSec=weekSessions.reduce((a,b)=>a+b.durationSec,0),deepSec=weekSessions.filter(s=>s.deepStatus==='deep').reduce((a,b)=>a+b.durationSec,0);const deepRatio=totalSec?Math.round(deepSec/totalSec*100):0;
  const actualQ=currentWeek?.actualQuestions||questions.length;const qCorrect=questions.filter(q=>q.isCorrect===true).length;const qAcc=questions.length?Math.round(qCorrect/questions.length*100):null;
  const weekDays=useMemo(()=>{const names=['周一','周二','周三','周四','周五','周六','周日'];if(!currentWeek)return names.map(day=>({day,hours:0,deep:0}));const start=new Date(`${currentWeek.startDate}T00:00:00`);return names.map((day,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);const key=d.toISOString().slice(0,10);const rows=weekSessions.filter(s=>s.date===key);return{day,hours:+(rows.reduce((a,b)=>a+b.durationSec,0)/3600).toFixed(1),deep:+(rows.filter(s=>s.deepStatus==='deep').reduce((a,b)=>a+b.durationSec,0)/3600).toFixed(1)}})},[currentWeek,weekSessions]);
  const targetH=Number(currentWeek?.targetHours||0),actualH=Number(currentWeek?.actualHours||0),hourPct=targetH?Math.min(100,Math.round(actualH/targetH*100)):0;const qualified=currentPhase?.criteria.filter(c=>c.passed).length||0;const criteriaTotal=currentPhase?.criteria.length||0;const gdModules=modules.filter(m=>m.examCode==='guangdong');

  return <WorkspacePage id="view-dashboard" className="mx-auto max-w-[1500px]">
    <PageHeader eyebrow={`W${currentWeek?.weekNo||'—'} · ${currentPhase?.code||'当前阶段'}`} title={tZen(currentPhase?.name||'备考工作台',zenMode)} subtitle={tZen(currentPhase?.goalMd||'用真实训练数据决定今天做什么、下一步练什么。',zenMode)} actions={<><QuietButton onClick={()=>setActiveTab('review')}><RotateCcw className="h-3.5 w-3.5"/>错题复训 · {pendingMistakes.length}</QuietButton><PrimaryButton onClick={()=>startTimer('资料分析','真题训练','pomodoro',1500)}><Play className="h-3.5 w-3.5"/>开始 25 分钟</PrimaryButton></>}/>

    <Surface pad="md" className="mb-5"><MetricRail columns="grid-cols-2 lg:grid-cols-4"><Metric compact label="本周有效时长" value={`${actualH.toFixed(1)}h`} note={`目标 ${targetH.toFixed(1)}h · ${hourPct}%`} icon={<Clock className="h-3.5 w-3.5"/>}/><Metric compact label="深度专注" value={`${deepRatio}%`} note={`${weekSessions.length} 次学习记录`} icon={<Target className="h-3.5 w-3.5"/>}/><Metric compact label="真实题量" value={`${actualQ}`} note={qAcc!==null?`正确率 ${qAcc}%`:'样本不足'} icon={<BookOpen className="h-3.5 w-3.5"/>}/><Metric compact label="阶段准出" value={`${qualified}/${criteriaTotal}`} note="只看硬性指标" icon={<BarChart3 className="h-3.5 w-3.5"/>}/></MetricRail></Surface>

    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.65fr)_minmax(320px,.75fr)]"><div className="space-y-5">
      <Surface pad="lg"><SectionHeader title="本周投入节奏" subtitle="把时间连续性和深度学习占比放在同一张图里；不追求装饰性图表。" action={<button onClick={()=>setActiveTab('study')} className="inline-flex items-center gap-1 text-[11px] font-semibold" style={{color:'var(--wb-accent-text)'}}>学习投入详情<ArrowRight className="h-3 w-3"/></button>}/><div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_190px]"><div className="flex h-56 items-end gap-3 px-1 pt-5">{weekDays.map(d=>{const maxH=Math.max(4,...weekDays.map(x=>x.hours));const totalPct=d.hours/maxH*100;const deepPct=d.hours?d.deep/d.hours*100:0;return <div key={d.day} className="flex h-full flex-1 flex-col items-center justify-end gap-2"><span className="font-mono text-[10px]" style={{color:'var(--wb-text-3)'}}>{d.hours?`${d.hours}h`:'—'}</span><div className="flex w-full max-w-[42px] flex-col justify-end overflow-hidden rounded-t-[6px]" style={{height:`${Math.max(8,totalPct)}%`,background:'var(--wb-surface-hover)'}}>{d.hours>0&&<><div className="w-full" style={{height:`${100-deepPct}%`,background:'var(--wb-border-strong)'}}/><div className="w-full" style={{height:`${deepPct}%`,background:'var(--wb-accent)'}}/></>}</div><span className="text-[10px] font-medium" style={{color:'var(--wb-text-3)'}}>{d.day}</span></div>})}</div><div className="rounded-[9px] border p-4" style={{background:'var(--wb-surface-subtle)',borderColor:'var(--wb-border)'}}><div className="text-[10px] font-semibold tracking-[0.06em] uppercase" style={{color:'var(--wb-text-3)'}}>本周读数</div><div className="mt-4 space-y-4"><div><div className="text-[10px]" style={{color:'var(--wb-text-3)'}}>目标达成</div><div className="mt-1 text-2xl font-semibold tracking-[-0.04em]" style={{color:'var(--wb-text)'}}>{hourPct}%</div><div className="mt-2 h-1 overflow-hidden rounded-full" style={{background:'var(--wb-surface-pressed)'}}><div className="h-full rounded-full" style={{width:`${hourPct}%`,background:'var(--wb-accent)'}}/></div></div><div><div className="text-[10px]" style={{color:'var(--wb-text-3)'}}>深度投入</div><div className="mt-1 text-lg font-semibold" style={{color:'var(--wb-text)'}}>{(deepSec/3600).toFixed(1)}h</div></div><div><div className="text-[10px]" style={{color:'var(--wb-text-3)'}}>待清理错题</div><button onClick={()=>setActiveTab('review')} className="mt-1 inline-flex items-center gap-1 text-lg font-semibold" style={{color:'var(--wb-danger)'}}>{pendingMistakes.length}<ArrowRight className="h-3.5 w-3.5"/></button></div></div></div></div></Surface>

      <Surface pad="lg"><SectionHeader title={tZen('广东省考模块能力差距',zenMode)} subtitle="按差距判断下一轮训练资源投向；模块行保持高密度、可快速扫描。" action={<button onClick={()=>setActiveTab('progress')} className="text-[11px] font-semibold" style={{color:'var(--wb-accent-text)'}}>完整表现看板 →</button>}/><div className="divide-y" style={{borderColor:'var(--wb-border)'}}>{gdModules.map(m=><div key={m.id} className="grid grid-cols-[132px_minmax(0,1fr)_96px] items-center gap-4 py-3 first:pt-0 last:pb-0" style={{borderColor:'var(--wb-border)'}}><div><div className="text-[12px] font-semibold" style={{color:'var(--wb-text)'}}>{tZen(m.name,zenMode)}</div><div className="mt-0.5 text-[9px]" style={{color:'var(--wb-text-3)'}}>{m.questionCount}题 · {m.targetMinutes}分钟</div></div><div><div className="mb-1.5 flex justify-between text-[9px]" style={{color:'var(--wb-text-3)'}}><span>目标 {Math.round(m.targetAccuracy*100)}%</span><span>{m.currentAccuracy!==null&&m.currentAccuracy!==undefined?`当前 ${Math.round(m.currentAccuracy*100)}%`:'样本不足'}</span></div><div className="h-1.5 overflow-hidden rounded-full" style={{background:'var(--wb-surface-pressed)'}}><div className="h-full rounded-full" style={{width:`${m.currentAccuracy?Math.round(m.currentAccuracy*100):0}%`,background:m.isQualified?'var(--wb-success)':'var(--wb-accent)'}}/></div></div><div className="text-right text-[10px] font-medium" style={{color:'var(--wb-text-2)'}}>{m.gapText}</div></div>)}</div></Surface>

      <Surface pad="lg"><SectionHeader title={`${currentPhase?.code||'当前'} 阶段准出条件`} subtitle="达标项降低视觉权重，未达标项保留明确提醒。"/><div className="grid gap-2 md:grid-cols-2">{currentPhase?.criteria.map(cr=><div key={cr.id} className="flex items-center justify-between gap-3 rounded-[8px] border px-3.5 py-3" style={{background:cr.passed?'var(--wb-success-soft)':'var(--wb-warning-soft)',borderColor:'var(--wb-border)'}}><div className="flex items-center gap-2.5">{cr.passed?<CheckCircle2 className="h-4 w-4" style={{color:'var(--wb-success)'}}/>:<AlertCircle className="h-4 w-4" style={{color:'var(--wb-warning)'}}/>}<span className="text-[11px] font-medium" style={{color:'var(--wb-text)'}}>{tZen(cr.label,zenMode)}</span></div><span className="font-mono text-[10px]" style={{color:'var(--wb-text-2)'}}>{cr.metric==='accuracy'?`${Math.round(cr.currentVal*100)}%`:cr.currentVal}</span></div>)}</div></Surface>
    </div><aside className="space-y-5">
      <Surface pad="lg"><SectionHeader title="今天先做什么" subtitle={`${pendingTasks.length} 个待办，只保留真正需要执行的下一步。`} action={<CheckSquare className="h-4 w-4" style={{color:'var(--wb-accent-text)'}}/>}/><div className="divide-y" style={{borderColor:'var(--wb-border)'}}>{tasks.slice(0,5).map(task=><div key={task.id} className={`group py-3 first:pt-0 last:pb-0 ${task.status==='done'?'opacity-55':''}`}><div className="flex items-start gap-3"><button onClick={()=>toggleTask(task.id)} className="mt-0.5 flex h-5 w-5 flex-shrink-0 items-center justify-center rounded-full border" style={{background:task.status==='done'?'var(--wb-success-soft)':'var(--wb-surface)',borderColor:task.status==='done'?'var(--wb-success)':'var(--wb-border-strong)',color:'var(--wb-success)'}}>{task.status==='done'?<CheckCircle2 className="h-3.5 w-3.5"/>:null}</button><div className="min-w-0 flex-1"><div className="flex items-center gap-2 text-[9px]"><span className="font-semibold" style={{color:task.priority==='P0'?'var(--wb-danger)':'var(--wb-warning)'}}>{task.priority}</span><span style={{color:'var(--wb-text-3)'}}>{task.estMinutes} min</span></div><div className={`mt-1 text-[12px] font-medium leading-5 ${task.status==='done'?'line-through':''}`} style={{color:task.status==='done'?'var(--wb-text-3)':'var(--wb-text)'}}>{tZen(task.title,zenMode)}</div><button onClick={()=>setActiveTab(task.actionUrl==='/review'?'review':'knowledge')} className="mt-1.5 inline-flex items-center gap-1 text-[10px] font-semibold" style={{color:'var(--wb-accent-text)'}}>执行<ArrowRight className="h-3 w-3"/></button></div></div></div>)}</div><button onClick={()=>setActiveTab('today')} className="mt-4 inline-flex items-center gap-1 text-[11px] font-medium" style={{color:'var(--wb-text-2)'}}>查看完整任务队列<ArrowRight className="h-3.5 w-3.5"/></button></Surface>

      <Surface pad="lg"><SectionHeader title="高频错误盯防" subtitle="只显示最值得复训的模式" action={<ShieldCheck className="h-4 w-4" style={{color:'var(--wb-danger)'}}/>}/><div className="space-y-2">{mistakes.slice(0,4).map(m=><button key={m.id} onClick={()=>setActiveTab('review')} className="w-full rounded-[8px] border px-3.5 py-3 text-left" style={{background:'var(--wb-surface-subtle)',borderColor:'var(--wb-border)'}}><div className="flex items-center justify-between"><span className="text-[10px] font-semibold" style={{color:'var(--wb-danger)'}}>{m.errorPattern}</span><span className="text-[9px]" style={{color:'var(--wb-text-3)'}}>M{m.masteryLevel}</span></div><div className="mt-1 line-clamp-2 text-[11px] leading-5" style={{color:'var(--wb-text-2)'}}>{m.errorPatternName}</div></button>)}</div><button onClick={()=>setActiveTab('mistakes')} className="mt-3 text-[11px] font-semibold" style={{color:'var(--wb-accent-text)'}}>进入错题库 →</button></Surface>

      <Surface pad="lg"><SectionHeader title="13 周里程碑" action={<TrendingUp className="h-4 w-4" style={{color:'var(--wb-accent-text)'}}/>}/><div className="space-y-1">{weekPlans.slice(0,5).map((w,i)=><div key={w.weekNo} className="flex items-center gap-3 rounded-[8px] px-2.5 py-2" style={{background:i===0?'var(--wb-accent-soft)':'transparent'}}><span className="flex h-6 w-6 items-center justify-center rounded-full text-[9px] font-semibold" style={{background:i===0?'var(--wb-accent)':'var(--wb-surface-hover)',color:i===0?'white':'var(--wb-text-3)'}}>W{w.weekNo}</span><div className="min-w-0 flex-1 truncate text-[11px] font-medium" style={{color:i===0?'var(--wb-text)':'var(--wb-text-2)'}}>{w.theme}</div>{i===0&&<span className="text-[9px] font-semibold" style={{color:'var(--wb-accent-text)'}}>NOW</span>}</div>)}</div><button onClick={()=>setActiveTab('weekplan')} className="mt-3 text-[11px] font-semibold" style={{color:'var(--wb-accent-text)'}}>打开周计划 →</button></Surface>
    </aside></div>
  </WorkspacePage>;
};
