import React,{useEffect,useMemo,useState} from 'react';
import {BookOpen,Check,ChevronDown,ChevronRight,GraduationCap,ListTree,Menu,Play,Plus,Search,Sparkles,Target,Trash2,TriangleAlert,X} from 'lucide-react';
import {useApp} from '../../context/AppContext';
import {KnowledgeSectionBlock,type KnowledgeSection} from '../knowledge/KnowledgeSectionBlock';
import {CopyButton} from '../common/CopyButton';
import {formatKnowledgeText} from '../../utils/copy';
import {tZen} from '../../utils/zen';
import type {MasteryState} from '../../types';

type Lens={label:string;focus:string;source:string;evidence?:string};
type Profile={positioning?:string;priority?:string[];exam_route?:string[];avoid?:string[];training?:string[];lenses?:Lens[];evidence_policy?:string};
type Section=KnowledgeSection;
type ReadingPack={slug:string;module:string;profile:Profile;sections:Section[];lesson_sections:Section[];toc?:{id:string;title:string;kind:string}[];evidence_policy?:string};
type Rec={slug:string;title:string;reason:string;score:number;module?:string;module_names?:unknown};
type Unit={id:string;title:string;trigger:string;action:string;stop:string};
type Expansion={id:string;type:string;text:string;source:string;status:string;anchor:string};
type Experience={slug:string;module:string;title:string;units:Unit[];sections:Section[];profile:Profile;data_band:{attempts:number;accuracy:number|null;avg_seconds?:number|null;recurrence:number;last_validation?:any;validation_count:number};adoptions:Record<string,{method_label:string;status:string}>;expansions:Record<string,Expansion[]>;degraded?:boolean;warnings?:string[]};
type ReadMode='lesson'|'full';

const kindLabel:Record<string,string>={recognition:'识别',method:'主方法',speed:'提速',example:'例题',boundary:'边界',review:'复盘',deep:'原理',other:'讲义'};
const masteryLabel:Record<MasteryState,{label:string;color:string}>={
  unlearned:{label:'未学习',color:'bg-stone-100 text-stone-600'},learning:{label:'学习中',color:'bg-blue-100 text-blue-800'},recovered:{label:'已恢复',color:'bg-amber-100 text-amber-900'},stable:{label:'稳定掌握',color:'bg-emerald-100 text-emerald-900'},mastered:{label:'考场熟练',color:'bg-purple-100 text-purple-900 font-bold'},
};
const expansionTypes=['为什么','边界','易混','陷阱','演示'] as const;

async function req<T=any>(url:string,init?:RequestInit):Promise<T>{
  const res=await fetch(url,{...init,headers:{...(init?.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(init?.headers||{})}});
  const body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body?.error?.message||body?.detail||`HTTP ${res.status}`);return body as T;
}

export const KnowledgeView:React.FC=()=>{
  const{knowledgeNodes,activeKnowledgeSlug,setActiveKnowledgeSlug,updateNodeMastery,zenMode}=useApp();
  const[q,setQ]=useState('');const[openModules,setOpenModules]=useState<Record<string,boolean>>({});const[mode,setMode]=useState<ReadMode>('lesson');
  const[reading,setReading]=useState<ReadingPack|null>(null);const[experience,setExperience]=useState<Experience|null>(null);const[unitId,setUnitId]=useState<string|null>(null);const[recs,setRecs]=useState<Rec[]>([]);
  const[loading,setLoading]=useState(false);const[readingError,setReadingError]=useState('');const[auxWarning,setAuxWarning]=useState('');const[busy,setBusy]=useState('');const[navOpen,setNavOpen]=useState(false);const[toolsOpen,setToolsOpen]=useState(false);

  const filtered=useMemo(()=>knowledgeNodes.filter(n=>!q.trim()||`${n.title}\n${n.module}\n${n.content}`.toLowerCase().includes(q.toLowerCase())),[knowledgeNodes,q]);
  const groups=useMemo(()=>{const map=new Map<string,typeof knowledgeNodes>();for(const node of filtered){if(!map.has(node.module))map.set(node.module,[]);map.get(node.module)!.push(node)}return Array.from(map.entries()).map(([module,nodes])=>({module,nodes}))},[filtered]);
  const current=knowledgeNodes.find(n=>n.slug===activeKnowledgeSlug)||filtered[0]||knowledgeNodes[0];

  useEffect(()=>{req<{items:Rec[];degraded:boolean;warning?:string|null}>('/api/v2/knowledge-safe/recommendations').then(p=>{setRecs(Array.isArray(p.items)?p.items:[]);if(p.warning)setAuxWarning(p.warning)}).catch(()=>setRecs([]))},[]);
  useEffect(()=>{
    if(!current)return;setOpenModules(prev=>({...prev,[current.module]:true}));setLoading(true);setReadingError('');setAuxWarning('');setExperience(null);setUnitId(null);
    const readingJob=req<ReadingPack>(`/api/knowledge/node/${encodeURIComponent(current.slug)}/reading`).then(setReading).catch((e:any)=>{setReading(null);setReadingError(e?.message||'阅读结构加载失败')});
    const experienceJob=req<Experience>(`/api/v2/knowledge-safe/${encodeURIComponent(current.slug)}/experience`).then(p=>{setExperience(p);setUnitId(p.units?.[0]?.id||null);if(p.warnings?.length)setAuxWarning(p.warnings.join('；'))}).catch((e:any)=>setAuxWarning(`个性化增强暂不可用：${e?.message||'读取失败'}`));
    void req(`/api/v2/knowledge/${encodeURIComponent(current.slug)}/view`,{method:'POST'}).catch(()=>{});Promise.allSettled([readingJob,experienceJob]).finally(()=>setLoading(false));
  },[current?.slug]);

  const sections=mode==='lesson'?(reading?.lesson_sections||[]):(reading?.sections||[]);const currentUnit=experience?.units.find(u=>u.id===unitId)||experience?.units?.[0];const expansions=currentUnit?(experience?.expansions?.[currentUnit.id]||[]):[];const adopted=currentUnit?experience?.adoptions?.[currentUnit.id]:undefined;const lenses=reading?.profile?.lenses||experience?.profile?.lenses||[];
  const scrollTo=(id:string)=>{document.getElementById(`lesson-${id}`)?.scrollIntoView({behavior:'smooth',block:'start'});setToolsOpen(false)};
  const selectNode=(slug:string)=>{setActiveKnowledgeSlug(slug);setNavOpen(false)};
  const startPractice=()=>{if(!current)return;window.dispatchEvent(new CustomEvent('gongkao:start-practice',{detail:{node_slug:current.slug,title:`${current.title} · 方法验证`,limit:5,estimated_minutes:8,adopted_method:adopted?.method_label||null,force:false}}))};
  const adopt=async(label:string)=>{if(!current||!currentUnit)return;setBusy(`adopt-${label}`);try{const row=await req(`/api/v2/knowledge/${encodeURIComponent(current.slug)}/adoption`,{method:'POST',body:JSON.stringify({unit_id:currentUnit.id,method_label:label,status:adopted?.method_label===label&&adopted?.status==='adopted'?'discarded':'adopted'})});setExperience(p=>p?{...p,adoptions:{...p.adoptions,[currentUnit.id]:row}}:p)}catch(e:any){setAuxWarning(e?.message||'方法状态保存失败')}finally{setBusy('')}};
  const generate=async(type:string,text?:string)=>{if(!current||!currentUnit)return;const key=`expand-${type}`;setBusy(key);try{const row=await req<Expansion>(`/api/v2/knowledge/${encodeURIComponent(current.slug)}/expansion`,{method:'POST',body:JSON.stringify({unit_id:currentUnit.id,anchor:currentUnit.trigger,type,text})});setExperience(p=>p?{...p,expansions:{...p.expansions,[currentUnit.id]:[...(p.expansions[currentUnit.id]||[]).filter(x=>x.type!==type),row]}}:p)}catch(e:any){setAuxWarning(e?.message||'补充生成失败')}finally{setBusy('')}};
  const mutate=async(id:string,action:'adopt'|'delete')=>{if(!currentUnit)return;setBusy(id);try{const rows=await req<Expansion[]>('/api/v2/knowledge/expansion/action',{method:'POST',body:JSON.stringify({unit_id:currentUnit.id,expansion_id:id,action})});setExperience(p=>p?{...p,expansions:{...p.expansions,[currentUnit.id]:rows}}:p)}catch(e:any){setAuxWarning(e?.message||'补充操作失败')}finally{setBusy('')}};

  const fallbackBody=!reading&&current?.content?current.content:'';
  const copyBody=sections.length?sections.map(s=>`## ${s.title}\n\n${s.body}`).join('\n\n'):current?.content||'';
  const copyWhole=current?formatKnowledgeText({title:current.title,module:current.module,body:copyBody}):'';
  const hasHints=!!reading&&Boolean(reading.profile.positioning||reading.profile.priority?.length||reading.profile.exam_route?.length||reading.profile.avoid?.length||reading.profile.training?.length||lenses.length);

  const directory=<><div className="p-4 border-b border-stone-200"><div className="flex items-center justify-between gap-3"><div><div className="text-[10px] font-mono text-amber-700">KNOWLEDGE</div><h2 className="text-base font-bold text-stone-900">{tZen('知识目录',zenMode)}</h2></div><button onClick={()=>setNavOpen(false)} className="p-1 text-stone-400 hover:text-stone-900"><X className="w-4 h-4"/></button></div><div className="relative mt-3"><Search className="w-3.5 h-3.5 absolute left-2.5 top-2.5 text-stone-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索考点..." className="w-full pl-8 pr-3 py-2 border border-stone-200 text-xs outline-none focus:border-stone-400"/></div></div>
    {recs.length>0&&<div className="p-3 border-b border-stone-100"><div className="text-[10px] font-semibold text-stone-500 mb-1.5">当前优先</div>{recs.slice(0,5).map(r=><button key={r.slug} onClick={()=>selectNode(r.slug)} className="w-full text-left py-1.5 px-1 hover:bg-stone-50"><div className="text-[11px] font-semibold text-stone-800 truncate">{r.title}</div><div className="text-[9px] text-stone-500 truncate">{r.reason}</div></button>)}</div>}
    <nav className="p-2 overflow-y-auto max-h-[calc(82vh-180px)]">{groups.map(group=>{const isOpen=!!openModules[group.module];return <div key={group.module} className="mb-1"><button onClick={()=>setOpenModules(p=>({...p,[group.module]:!isOpen}))} className="w-full px-2 py-2 flex items-center justify-between text-xs font-semibold text-stone-800 hover:bg-stone-50"><span>{tZen(group.module,zenMode)}</span><span className="flex items-center gap-1 text-[10px] text-stone-400">{group.nodes.length}{isOpen?<ChevronDown className="w-3 h-3"/>:<ChevronRight className="w-3 h-3"/>}</span></button>{isOpen&&<div className="ml-2 pl-2 border-l border-stone-200">{group.nodes.map(node=><button key={node.slug} onClick={()=>selectNode(node.slug)} className={`w-full px-2 py-2 text-left text-[11px] leading-4 ${current?.slug===node.slug?'bg-stone-900 text-white':'text-stone-600 hover:bg-stone-50'}`}><div className="font-medium">{node.title}</div><div className={`mt-0.5 text-[9px] ${current?.slug===node.slug?'text-stone-300':'text-stone-400'}`}>{masteryLabel[node.mastery]?.label||'未学习'} · {node.sampleN||0}题</div></button>)}</div>}</div>})}</nav></>;

  const tools=<><div className="p-4 border-b border-stone-200 flex items-center justify-between"><div className="text-sm font-bold text-stone-900">本节导航与工具</div><button onClick={()=>setToolsOpen(false)} className="p-1 text-stone-400 hover:text-stone-900"><X className="w-4 h-4"/></button></div><div className="p-4 space-y-5 overflow-y-auto max-h-[calc(84vh-58px)]">
    {current&&<section><div className="text-[10px] font-semibold text-stone-500 mb-2">掌握状态</div><div className="flex flex-wrap gap-1.5">{(['unlearned','learning','recovered','stable','mastered'] as MasteryState[]).map(st=><button key={st} onClick={()=>void updateNodeMastery(current.slug,st)} className={`px-2.5 py-1.5 text-[10px] border ${current.mastery===st?'bg-stone-900 text-white border-stone-900':'bg-white text-stone-600 border-stone-200'}`}>{masteryLabel[st].label}{current.mastery===st&&<Check className="inline ml-1 w-3 h-3"/>}</button>)}</div></section>}
    {reading&&<section className="border-t border-stone-200 pt-4"><div className="flex items-center gap-1.5 text-[10px] font-semibold text-stone-500 mb-2"><ListTree className="w-3.5 h-3.5"/>本节目录</div><div className="space-y-0.5">{sections.map((s,i)=><button key={s.id} onClick={()=>scrollTo(s.id)} className="w-full py-1.5 text-left text-[10px] text-stone-600 hover:text-stone-950"><span className="font-mono text-stone-300 mr-1.5">{String(i+1).padStart(2,'0')}</span><span className="text-stone-400 mr-1">{kindLabel[s.kind]||'讲义'} ·</span>{s.title}</button>)}</div></section>}
    {experience&&currentUnit&&<section className="border-t border-stone-200 pt-4"><div className="text-[10px] font-semibold text-stone-500 mb-2">情形与扩写</div>{experience.units.length>1&&<select value={currentUnit.id} onChange={e=>setUnitId(e.target.value)} className="w-full mb-3 px-2 py-1.5 border border-stone-200 bg-white text-[10px]">{experience.units.map(u=><option key={u.id} value={u.id}>{u.title}</option>)}</select>}<div className="text-[11px] leading-5 text-stone-700"><b>信号：</b>{currentUnit.trigger}<br/><b>动作：</b>{currentUnit.action}{currentUnit.stop&&<><br/><b>止损：</b>{currentUnit.stop}</>}</div><div className="mt-3 flex flex-wrap gap-1">{expansionTypes.map(type=><button key={type} disabled={!!busy} onClick={()=>void generate(type)} className="px-2 py-1 border border-stone-200 bg-stone-50 text-[10px]">{busy===`expand-${type}`?'生成中…':`+ ${type}`}</button>)}<button disabled={!!busy} onClick={()=>{const text=window.prompt('写下你的批注');if(text)void generate('我的批注',text)}} className="px-2 py-1 border border-stone-200 bg-white text-[10px]"><Plus className="w-3 h-3 inline"/> 批注</button></div>{expansions.length>0&&<div className="mt-3 space-y-2">{expansions.map(row=><div key={row.id} className="p-2.5 bg-stone-50 border border-stone-100"><div className="flex items-center justify-between gap-2"><span className="text-[9px] font-semibold text-stone-500">{row.type} · {row.source}</span><div className="flex items-center gap-2"><CopyButton text={row.text} label="复制"/><button disabled={busy===row.id||row.status==='adopted'} onClick={()=>void mutate(row.id,'adopt')} className="text-[9px] text-stone-500">采纳</button><button disabled={busy===row.id} onClick={()=>void mutate(row.id,'delete')} className="text-stone-400 hover:text-rose-700"><Trash2 className="w-3 h-3"/></button></div></div><div className="mt-1 text-[11px] leading-5 text-stone-700 whitespace-pre-wrap">{row.text}</div></div>)}</div>}</section>}
    {experience&&<section className="border-t border-stone-200 pt-4"><div className="text-[10px] font-semibold text-stone-500 mb-2">真实训练证据</div><div className="text-xs text-stone-700">做过 {experience.data_band.attempts} 题 · 正确率 {experience.data_band.accuracy==null?'—':`${Math.round(experience.data_band.accuracy*100)}%`} · 复发 {experience.data_band.recurrence} 次</div><button onClick={startPractice} className="mt-3 w-full px-3 py-2 bg-stone-900 text-white text-[10px] font-semibold inline-flex items-center justify-center gap-1"><Play className="w-3 h-3"/>练 5 题验证</button></section>}
  </div></>;

  return <div id="view-knowledge" className="px-3 py-4 md:px-6 md:py-6 max-w-[1240px] mx-auto">
    {(navOpen||toolsOpen)&&<button aria-label="关闭浮层" onClick={()=>{setNavOpen(false);setToolsOpen(false)}} className="fixed inset-0 z-30 bg-stone-950/15 backdrop-blur-[1px]"/>}
    {navOpen&&<aside className="fixed z-40 top-20 left-4 w-[min(350px,calc(100vw-32px))] max-h-[82vh] bg-white border border-stone-300 shadow-xl overflow-hidden">{directory}</aside>}
    {toolsOpen&&<aside className="fixed z-40 top-20 right-4 w-[min(360px,calc(100vw-32px))] max-h-[84vh] bg-white border border-stone-300 shadow-xl overflow-hidden">{tools}</aside>}

    <div className="sticky top-2 z-20 mb-3 flex items-center justify-between gap-3 pointer-events-none"><button onClick={()=>{setNavOpen(v=>!v);setToolsOpen(false)}} className="pointer-events-auto px-3 py-2 bg-white/95 border border-stone-300 shadow-sm text-xs font-medium text-stone-700 inline-flex items-center gap-1.5"><Menu className="w-3.5 h-3.5"/>目录</button><button onClick={()=>{setToolsOpen(v=>!v);setNavOpen(false)}} className="pointer-events-auto px-3 py-2 bg-white/95 border border-stone-300 shadow-sm text-xs font-medium text-stone-700 inline-flex items-center gap-1.5"><ListTree className="w-3.5 h-3.5"/>本节工具</button></div>

    {current?<article className="bg-[#fffdfa] border border-stone-200">
      <header className="px-5 py-5 md:px-9 md:py-7 border-b border-stone-200 bg-white"><div className="flex items-start justify-between gap-5"><div className="min-w-0"><div className="text-[11px] text-stone-500 mb-2">{tZen(current.module,zenMode)}{current.targetSeconds?` · 目标 ${current.targetSeconds}s/题`:''}</div><h1 className="text-2xl md:text-[30px] font-bold text-stone-950 leading-tight tracking-tight">{current.title}</h1>{experience&&<div className="mt-2 text-[11px] text-stone-500">做过 {experience.data_band.attempts} 题 · 正确率 {experience.data_band.accuracy==null?'—':`${Math.round(experience.data_band.accuracy*100)}%`} · 关联复发 {experience.data_band.recurrence} 次</div>}</div><CopyButton text={copyWhole} label="复制整节" className="flex-shrink-0 mt-1"/></div><div className="mt-5 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-1 border border-stone-200 bg-stone-50 p-1"><button onClick={()=>setMode('lesson')} className={`px-3 py-1.5 text-xs font-semibold ${mode==='lesson'?'bg-white text-stone-900 shadow-sm':'text-stone-500'}`}>精讲</button><button onClick={()=>setMode('full')} className={`px-3 py-1.5 text-xs font-semibold ${mode==='full'?'bg-white text-stone-900 shadow-sm':'text-stone-500'}`}>完整讲义</button></div><button onClick={startPractice} className="px-3 py-2 bg-stone-900 text-white text-xs font-semibold inline-flex items-center gap-1.5"><Play className="w-3.5 h-3.5"/>按这个方法练 5 题</button></div></header>
      {auxWarning&&<div className="mx-5 md:mx-9 mt-5 px-3 py-2 bg-amber-50 border border-amber-200 text-[11px] text-amber-900">{auxWarning}。正文阅读不受影响。</div>}
      {loading&&<div className="p-16 text-center text-sm text-stone-400">正在整理本节内容…</div>}
      {!loading&&reading&&<div className="px-4 py-6 md:px-9 md:py-9"><div className="max-w-[920px] mx-auto">
        {mode==='lesson'&&currentUnit&&<section className="mb-7 border-y border-amber-200 bg-amber-50/60"><div className="px-4 py-2 text-[10px] font-bold text-amber-900 border-b border-amber-200">30 秒考场唤醒</div><div className="grid grid-cols-1 md:grid-cols-3"><div className="p-4 md:border-r border-amber-200"><div className="text-[10px] text-amber-800">看到</div><div className="mt-1 text-sm font-semibold leading-6">{currentUnit.trigger}</div></div><div className="p-4 md:border-r border-t md:border-t-0 border-amber-200"><div className="text-[10px] text-amber-800">就做</div><div className="mt-1 text-sm font-semibold leading-6">{currentUnit.action}</div></div><div className="p-4 border-t md:border-t-0 border-amber-200"><div className="text-[10px] text-amber-800">切换 / 止损</div><div className="mt-1 text-sm leading-6 text-stone-700">{currentUnit.stop||'出现不适用信号时切回基础方法。'}</div></div></div></section>}
        {mode==='lesson'&&hasHints&&<details className="mb-8 border-y border-stone-200 bg-white group"><summary className="cursor-pointer list-none px-1 py-3 flex items-center justify-between gap-3"><div><span className="text-xs font-bold text-stone-800">学习提示与讲法</span>{reading.profile.positioning&&<span className="ml-2 text-[11px] text-stone-500">{reading.profile.positioning}</span>}</div><ChevronDown className="w-4 h-4 text-stone-400 group-open:rotate-180 transition-transform"/></summary><div className="pb-5 pt-2 grid grid-cols-1 lg:grid-cols-2 gap-x-7 gap-y-5">
          {reading.profile.priority?.length?<div><div className="flex items-center gap-1.5 text-[10px] font-bold text-stone-500 mb-2"><Target className="w-3.5 h-3.5"/>学习重点</div><ol className="space-y-1.5 text-xs leading-5 text-stone-700">{reading.profile.priority.map((x,i)=><li key={i}>{i+1}. {x}</li>)}</ol></div>:null}
          {reading.profile.exam_route?.length?<div><div className="text-[10px] font-bold text-stone-500 mb-2">考场调用链</div><ol className="space-y-1.5 text-xs leading-5 text-stone-700">{reading.profile.exam_route.map((x,i)=><li key={i}>{i+1}. {x}</li>)}</ol></div>:null}
          {reading.profile.avoid?.length?<div><div className="flex items-center gap-1.5 text-[10px] font-bold text-rose-700 mb-2"><TriangleAlert className="w-3.5 h-3.5"/>不要这样做</div><ul className="space-y-1.5 text-xs leading-5 text-stone-700">{reading.profile.avoid.map((x,i)=><li key={i}>• {x}</li>)}</ul></div>:null}
          {reading.profile.training?.length?<div><div className="flex items-center gap-1.5 text-[10px] font-bold text-emerald-700 mb-2"><GraduationCap className="w-3.5 h-3.5"/>怎么练</div><ul className="space-y-1.5 text-xs leading-5 text-stone-700">{reading.profile.training.map((x,i)=><li key={i}>• {x}</li>)}</ul></div>:null}
          {lenses.length>0&&<div className="lg:col-span-2 border-t border-stone-100 pt-4"><div className="flex items-center gap-1.5 text-[10px] font-bold text-stone-500 mb-2"><Sparkles className="w-3.5 h-3.5 text-amber-600"/>不同讲法</div><div className="grid grid-cols-1 md:grid-cols-2 gap-2">{lenses.map((lens,i)=><div key={`${lens.label}-${i}`} className="border border-stone-200 p-3"><div className="flex items-center justify-between gap-2"><span className="text-xs font-bold">{lens.label}</span><div className="flex items-center gap-2"><CopyButton text={`${lens.label}\n${lens.focus}\n来源：${lens.source}`} label="复制"/><button disabled={busy===`adopt-${lens.label}`} onClick={()=>void adopt(lens.label)} className={`px-2 py-1 text-[10px] border ${adopted?.method_label===lens.label&&adopted?.status==='adopted'?'bg-stone-900 text-white border-stone-900':'bg-white border-stone-200 text-stone-600'}`}>{adopted?.method_label===lens.label&&adopted?.status==='adopted'?'已采用':'采用'}</button></div></div><p className="mt-2 text-xs leading-5 text-stone-700">{lens.focus}</p><div className="mt-1 text-[9px] text-stone-400">来源：{lens.source}</div></div>)}</div></div>}
        </div></details>}
        <div className="space-y-8">{sections.map(section=><KnowledgeSectionBlock key={section.id} section={section} module={current.module}/>)}</div>
      </div></div>}
      {!loading&&!reading&&fallbackBody&&<div className="px-4 py-6 md:px-9 md:py-9"><div className="max-w-[920px] mx-auto"><div className="mb-4 text-xs text-amber-800">阅读结构暂不可用，已回退到原始笔记。</div><KnowledgeSectionBlock section={{id:'raw-note',title:'原始笔记正文',kind:'other',body:fallbackBody}} module={current.module}/></div></div>}
      {!loading&&!reading&&!fallbackBody&&<div className="p-10 text-center text-sm text-rose-700">知识正文加载失败：{readingError||'暂无可用正文'}</div>}
    </article>:<div className="p-16 bg-white border border-stone-200 text-center text-sm text-stone-400">请选择一个考点</div>}
  </div>;
};
