import React,{useEffect,useMemo,useState} from 'react';
import Markdown from 'react-markdown';
import {BookOpen,Check,ChevronDown,ChevronRight,GraduationCap,ListTree,Search,Sparkles,Target,TriangleAlert} from 'lucide-react';
import {useApp} from '../../context/AppContext';
import {tZen} from '../../utils/zen';
import type {MasteryState} from '../../types';

type Lens={label:string;focus:string;source:string;evidence:string};
type Profile={positioning:string;priority:string[];exam_route:string[];avoid:string[];training:string[];lenses:Lens[];evidence_policy?:string};
type Section={id:string;title:string;kind:string;level:number;body:string};
type ReadingPack={slug:string;module:string;profile:Profile;sections:Section[];lesson_sections:Section[];toc:{id:string;title:string;kind:string}[];evidence_policy:string};

type ReadMode='lesson'|'full';
const kindLabel:Record<string,string>={recognition:'识别',method:'主方法',speed:'考场提速',example:'例题',boundary:'边界易错',review:'训练复盘',deep:'原理',other:'讲义'};

export const KnowledgeView:React.FC=()=>{
  const{knowledgeNodes,activeKnowledgeSlug,setActiveKnowledgeSlug,updateNodeMastery,zenMode}=useApp();
  const[q,setQ]=useState('');const[openModules,setOpenModules]=useState<Record<string,boolean>>({});const[mode,setMode]=useState<ReadMode>('lesson');const[reading,setReading]=useState<ReadingPack|null>(null);const[readingError,setReadingError]=useState('');const[loading,setLoading]=useState(false);
  const filtered=useMemo(()=>knowledgeNodes.filter(n=>!q.trim()||`${n.title}\n${n.module}\n${n.content}`.toLowerCase().includes(q.toLowerCase())),[knowledgeNodes,q]);
  const groups=useMemo(()=>{const map=new Map<string,typeof knowledgeNodes>();for(const n of filtered){if(!map.has(n.module))map.set(n.module,[]);map.get(n.module)!.push(n)}return Array.from(map.entries()).map(([module,nodes])=>({module,nodes}))},[filtered]);
  const current=knowledgeNodes.find(n=>n.slug===activeKnowledgeSlug)||filtered[0]||knowledgeNodes[0];
  const labels:Record<MasteryState,{label:string;color:string}>={unlearned:{label:'未学习',color:'bg-stone-100 text-stone-600'},learning:{label:'学习中',color:'bg-blue-100 text-blue-800'},recovered:{label:'已快速恢复',color:'bg-amber-100 text-amber-900'},stable:{label:'稳定掌握',color:'bg-emerald-100 text-emerald-900'},mastered:{label:'考场熟练',color:'bg-purple-100 text-purple-900 font-bold'}};

  useEffect(()=>{if(!current)return;setOpenModules(p=>({...p,[current.module]:true}));setLoading(true);setReadingError('');fetch(`/api/knowledge/node/${encodeURIComponent(current.slug)}/reading`).then(async r=>{if(!r.ok){let msg=`HTTP ${r.status}`;try{const p=await r.json();msg=p?.error?.message||p?.detail||msg}catch{}throw new Error(msg)}return r.json()}).then((p:ReadingPack)=>setReading(p)).catch(e=>{setReading(null);setReadingError(e?.message||'读取失败')}).finally(()=>setLoading(false))},[current?.slug]);

  const sections=mode==='lesson'?(reading?.lesson_sections||[]):(reading?.sections||[]);
  const scrollTo=(id:string)=>document.getElementById(`lesson-${id}`)?.scrollIntoView({behavior:'smooth',block:'start'});

  return <div id="view-knowledge" className="p-3 md:p-6 max-w-[1580px] mx-auto"><div className="grid grid-cols-1 xl:grid-cols-[260px_minmax(0,1fr)_230px] gap-4 items-start">
    <aside className="bg-white border border-stone-200 rounded-2xl overflow-hidden xl:sticky xl:top-3"><div className="px-4 py-4 border-b border-stone-100"><div className="text-[10px] font-mono text-amber-700 mb-1">XINGCE KNOWLEDGE</div><h2 className="text-base font-bold text-stone-900">{tZen('行测知识目录',zenMode)}</h2><p className="text-[11px] text-stone-500 mt-1">模块 → 考点，像教材目录一样进入</p><div className="relative mt-3"><Search className="w-3.5 h-3.5 absolute left-2.5 top-2.5 text-stone-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索考点..." className="w-full pl-8 pr-3 py-2 rounded-lg border border-stone-200 text-xs outline-none focus:border-stone-400"/></div></div><nav className="p-2 max-h-[calc(100vh-180px)] overflow-y-auto">{groups.map(group=>{const open=!!openModules[group.module];return <div key={group.module} className="mb-1"><button onClick={()=>setOpenModules(p=>({...p,[group.module]:!open}))} className="w-full px-2.5 py-2 rounded-lg flex items-center justify-between text-xs font-semibold text-stone-800 hover:bg-stone-50"><span>{tZen(group.module,zenMode)}</span><span className="flex items-center gap-1 text-[10px] text-stone-400 font-mono">{group.nodes.length}{open?<ChevronDown className="w-3 h-3"/>:<ChevronRight className="w-3 h-3"/>}</span></button>{open&&<div className="ml-2 pl-2 border-l border-stone-200 space-y-0.5">{group.nodes.map(n=>{const active=current?.slug===n.slug;return <button key={n.slug} onClick={()=>setActiveKnowledgeSlug(n.slug)} className={`w-full px-2.5 py-2 rounded-lg text-left ${active?'bg-stone-900 text-white':'text-stone-600 hover:bg-stone-50'}`}><div className="flex items-start gap-2"><span className={`mt-0.5 text-[9px] font-mono px-1 py-0.5 rounded ${active?'bg-stone-800 text-amber-300':'bg-stone-100 text-stone-400'}`}>B{n.priorityBatch||'—'}</span><div className="min-w-0"><div className="text-[11px] font-medium leading-4">{n.title}</div><div className={`text-[9px] mt-1 ${active?'text-stone-400':'text-stone-400'}`}>{labels[n.mastery]?.label||'未学习'} · {n.sampleN||0}题</div></div></div></button>})}</div>}</div>})}</nav></aside>

    <main className="min-w-0">{current?<article className="bg-[#fffdfa] border border-stone-200 rounded-3xl overflow-hidden shadow-2xs"><header className="px-5 py-6 md:px-9 md:py-8 border-b border-stone-200 bg-white"><div className="flex flex-wrap items-center gap-2 mb-3"><span className="px-2.5 py-1 rounded-full bg-stone-100 text-stone-700 text-[10px] font-semibold">{tZen(current.module,zenMode)}</span><span className="px-2 py-1 rounded-full bg-amber-50 text-amber-800 border border-amber-200 text-[10px] font-mono">B{current.priorityBatch||'—'}</span>{current.targetSeconds&&<span className="text-[10px] text-stone-500 font-mono">目标 {current.targetSeconds}s/题</span>}</div><h1 className="text-2xl md:text-3xl font-bold text-stone-950 leading-tight tracking-tight">{current.title}</h1><div className="mt-3 flex flex-wrap items-center gap-3 text-[10px] text-stone-500"><span>{current.charCount||current.content.length} 字</span><span>{current.sampleN||0} 题真实样本</span>{current.accuracy!=null&&<span>正确率 {(Number(current.accuracy)*100).toFixed(0)}%</span>}</div><div className="mt-5 flex items-center gap-1 p-1 rounded-xl bg-stone-100 w-fit"><button onClick={()=>setMode('lesson')} className={`px-3 py-1.5 rounded-lg text-xs font-semibold ${mode==='lesson'?'bg-white text-stone-900 shadow-sm':'text-stone-500'}`}>精讲模式</button><button onClick={()=>setMode('full')} className={`px-3 py-1.5 rounded-lg text-xs font-semibold ${mode==='full'?'bg-white text-stone-900 shadow-sm':'text-stone-500'}`}>完整讲义</button></div></header>

      {loading?<div className="p-16 text-center text-sm text-stone-400">正在整理本节阅读结构…</div>:readingError?<div className="p-10 text-center text-sm text-rose-700">知识阅读结构加载失败：{readingError}</div>:reading&&<div className="px-5 py-7 md:px-9 md:py-10"><div className="max-w-[820px] mx-auto">
        {mode==='lesson'&&<><section className="mb-9"><div className="flex items-center gap-2 text-[11px] font-bold text-stone-500 mb-3"><Target className="w-4 h-4"/>本节定位</div><p className="text-lg md:text-xl font-semibold leading-8 text-stone-900">{reading.profile.positioning}</p></section><section className="mb-9 grid grid-cols-1 md:grid-cols-2 gap-5"><div><div className="text-[11px] font-bold text-stone-500 mb-3">这一节真正要抓住的</div><ol className="space-y-3">{reading.profile.priority.map((x,i)=><li key={i} className="flex gap-3"><span className="w-6 h-6 rounded-full bg-stone-900 text-white text-[10px] font-mono flex items-center justify-center flex-shrink-0">{i+1}</span><span className="text-sm leading-6 text-stone-800">{x}</span></li>)}</ol></div><div><div className="text-[11px] font-bold text-stone-500 mb-3">考场调用链</div><div className="space-y-2">{reading.profile.exam_route.map((x,i)=><div key={i} className="flex items-center gap-2 text-sm text-stone-800"><span className="text-amber-700 font-mono text-[10px]">{String(i+1).padStart(2,'0')}</span><ChevronRight className="w-3 h-3 text-stone-300"/><span>{x}</span></div>)}</div></div></section>{reading.profile.lenses.length>0&&<section className="mb-10"><div className="flex items-center gap-2 text-[11px] font-bold text-stone-500 mb-3"><Sparkles className="w-4 h-4 text-amber-600"/>Skill 讲法 · 本节侧重</div><div className="space-y-3">{reading.profile.lenses.map((lens,i)=><div key={i} className="pl-4 border-l-2 border-amber-300 py-1"><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-bold text-stone-900">{lens.label}</span><span className="text-[9px] px-1.5 py-0.5 rounded bg-stone-100 text-stone-500">二级整理</span></div><p className="mt-1.5 text-sm leading-6 text-stone-700">{lens.focus}</p><div className="mt-1 text-[9px] text-stone-400">来源：{lens.source}</div></div>)}</div><p className="mt-3 text-[10px] text-stone-400 leading-5">{reading.evidence_policy}</p></section></>}

        <div className="space-y-10">{sections.map(section=><section id={`lesson-${section.id}`} key={section.id} className="scroll-mt-6"><div className="flex items-center gap-2 mb-3"><span className="text-[9px] font-semibold px-1.5 py-0.5 rounded bg-stone-100 text-stone-500">{kindLabel[section.kind]||'讲义'}</span><h2 className="text-lg font-bold text-stone-950">{section.title}</h2></div><div className="knowledge-reader prose prose-stone max-w-none prose-p:text-[14px] prose-p:leading-7 prose-li:text-[14px] prose-li:leading-7 prose-headings:tracking-tight prose-strong:text-stone-950"><Markdown>{section.body}</Markdown></div></section>)}</div>

        {mode==='lesson'&&<section className="mt-12 pt-8 border-t border-stone-200 grid grid-cols-1 md:grid-cols-2 gap-5"><div className="p-4 rounded-2xl bg-rose-50/60 border border-rose-200"><div className="flex items-center gap-2 text-xs font-bold text-rose-950 mb-3"><TriangleAlert className="w-4 h-4"/>不要这样做</div><ul className="space-y-2">{reading.profile.avoid.map((x,i)=><li key={i} className="text-xs leading-5 text-rose-900">• {x}</li>)}</ul></div><div className="p-4 rounded-2xl bg-emerald-50/60 border border-emerald-200"><div className="flex items-center gap-2 text-xs font-bold text-emerald-950 mb-3"><GraduationCap className="w-4 h-4"/>这节怎么练</div><ul className="space-y-2">{reading.profile.training.map((x,i)=><li key={i} className="text-xs leading-5 text-emerald-900">• {x}</li>)}</ul></div></section>}
      </div></div>}
    </article>:<div className="p-16 bg-white border border-stone-200 rounded-3xl text-center text-sm text-stone-400">请选择一个考点</div>}</main>

    <aside className="space-y-3 xl:sticky xl:top-3">{current&&<div className="bg-white border border-stone-200 rounded-2xl p-3"><div className="text-[10px] font-semibold text-stone-500 mb-2">掌握状态</div><div className="space-y-1">{(['unlearned','learning','recovered','stable','mastered'] as MasteryState[]).map(st=>{const active=current.mastery===st;return <button key={st} onClick={()=>updateNodeMastery(current.slug,st)} className={`w-full px-2.5 py-2 rounded-lg flex items-center justify-between text-[11px] ${active?'bg-stone-900 text-white':'text-stone-600 hover:bg-stone-50'}`}><span>{labels[st].label}</span>{active&&<Check className="w-3.5 h-3.5 text-emerald-400"/>}</button>})}</div></div>}{reading&&<div className="bg-white border border-stone-200 rounded-2xl p-3"><div className="flex items-center gap-1.5 text-[10px] font-semibold text-stone-500 mb-2"><ListTree className="w-3.5 h-3.5"/>本节目录</div><div className="max-h-[56vh] overflow-y-auto space-y-0.5">{(mode==='lesson'?reading.lesson_sections:reading.sections).map((s,i)=><button key={s.id} onClick={()=>scrollTo(s.id)} className="w-full px-2 py-1.5 rounded-lg text-left text-[10px] text-stone-600 hover:bg-stone-50 hover:text-stone-900"><span className="font-mono text-stone-300 mr-1.5">{String(i+1).padStart(2,'0')}</span>{s.title}</button>)}</div></div>}<div className="p-3 rounded-2xl bg-stone-900 text-stone-200"><div className="flex items-center gap-1.5 text-[10px] font-semibold text-amber-300"><BookOpen className="w-3.5 h-3.5"/>阅读原则</div><p className="mt-2 text-[10px] leading-5 text-stone-400">先理解“为什么这么做”和“什么时候该想到”，再记步骤。正确但超时、蒙对、绕路都不算稳定掌握。</p></div></aside>
  </div></div>;
};
