import React,{useEffect,useMemo,useState} from 'react';
import {BookOpen,ChevronRight,Compass,Search,Route,ShieldAlert,Lightbulb,Menu,X,FileText,Play,Copy} from 'lucide-react';
import {useApp} from '../../context/AppContext';
import {CopyButton} from '../common/CopyButton';
import {formatMethodText} from '../../utils/copy';
import {tZen} from '../../utils/zen';
import {WorkspacePage,PrimaryButton} from '../common/WorkspaceUi';

type FilterMode='all'|'call'|'boundary'|'example';
type DetailTab='principle'|'example'|'boundary'|'source';
type MethodRow={id:string;title:string;module:string;category:string;definition:string;principle:string;signals:string[];steps:string[];example:string;boundary:string;exam_command:string;source_note?:string;evidence?:string;node_slug?:string|null};

export const MethodsView:React.FC=()=>{
  const{methods,zenMode}=useApp();
  const[rows,setRows]=useState<MethodRow[]>([]);const[q,setQ]=useState('');const[filter,setFilter]=useState<FilterMode>('all');const[module,setModule]=useState('');const[category,setCategory]=useState('');const[selectedId,setSelectedId]=useState('');const[directoryOpen,setDirectoryOpen]=useState(false);const[detailTab,setDetailTab]=useState<DetailTab>('principle');
  useEffect(()=>{let alive=true;fetch('/api/knowledge/methods').then(async r=>r.ok?r.json():Promise.reject()).then((data:MethodRow[])=>{if(!alive)return;setRows(data);if(data[0]){setModule(data[0].module);setCategory(data[0].category);setSelectedId(data[0].id)}}).catch(()=>{const fallback=methods.map(m=>({id:m.id,title:m.title,module:m.module,category:m.category||'未分类',definition:m.definition,principle:m.principle,signals:m.signals,steps:m.steps,example:m.example,boundary:m.boundary,exam_command:m.callCommand}));if(alive){setRows(fallback);if(fallback[0]){setModule(fallback[0].module);setCategory(fallback[0].category);setSelectedId(fallback[0].id)}}});return()=>{alive=false}},[methods]);
  const directory=useMemo(()=>{const map=new Map<string,Map<string,number>>();for(const row of rows){if(!map.has(row.module))map.set(row.module,new Map());const cats=map.get(row.module)!;cats.set(row.category,(cats.get(row.category)||0)+1)}return Array.from(map.entries()).map(([name,cats])=>({name,count:Array.from(cats.values()).reduce((a,b)=>a+b,0),children:Array.from(cats.entries()).map(([name,count])=>({name,count}))}))},[rows]);
  const categories=directory.find(x=>x.name===module)?.children||directory[0]?.children||[];
  const list=useMemo(()=>rows.filter(m=>(!module||m.module===module)&&(!category||m.category===category)&&(filter==='all'||(filter==='call'&&!!m.exam_command)||(filter==='boundary'&&!!m.boundary)||(filter==='example'&&!!m.example))&&(!q.trim()||`${m.id}\n${m.title}\n${m.definition}\n${m.principle}\n${m.signals.join('\n')}`.toLowerCase().includes(q.toLowerCase()))),[rows,module,category,filter,q]);
  useEffect(()=>{if(!list.length){setSelectedId('');return}if(!list.some(x=>x.id===selectedId))setSelectedId(list[0].id)},[list,selectedId]);
  const current=rows.find(x=>x.id===selectedId)||list[0];
  const filters:{id:FilterMode;label:string}[]=[{id:'all',label:'全部'},{id:'call',label:'有口令'},{id:'boundary',label:'有边界'},{id:'example',label:'有例证'}];
  const detailTabs:{id:DetailTab;label:string;icon:React.ComponentType<{className?:string}>}[]=[{id:'principle',label:'原理',icon:BookOpen},{id:'example',label:'例题',icon:Play},{id:'boundary',label:'边界',icon:ShieldAlert},{id:'source',label:'来源',icon:FileText}];
  const chooseModule=(m:string)=>{setModule(m);setQ('');const firstCategory=directory.find(x=>x.name===m)?.children[0]?.name||'';setCategory(firstCategory);const hit=rows.find(x=>x.module===m&&(!firstCategory||x.category===firstCategory));if(hit)setSelectedId(hit.id)};
  const chooseCategory=(c:string)=>{setCategory(c);setQ('');const hit=rows.find(x=>x.module===module&&x.category===c);if(hit)setSelectedId(hit.id)};
  const chooseMethod=(id:string)=>{setSelectedId(id);setDirectoryOpen(false);setDetailTab('principle')};
  const copyCurrent=current?formatMethodText(current):'';

  if(!current)return <WorkspacePage id="view-methods"><div className="p-10 text-center text-sm" style={{color:'var(--wb-text-2)'}}>从方法索引选择一个方法</div></WorkspacePage>;
  const detailText=detailTab==='principle'?current.principle:detailTab==='example'?(current.example||'暂无实战例证'):detailTab==='boundary'?(current.boundary||'暂无边界说明'):`来源：${current.source_note||'—'}${current.evidence?`\n\n证据：${current.evidence}`:''}`;

  const directoryPanel=<div className="flex h-full min-h-0 flex-col" style={{background:'var(--wb-sidebar)'}}>
    <div className="border-b p-3.5" style={{borderColor:'var(--wb-border)'}}><div className="flex items-center justify-between gap-3"><div><div className="text-[12px] font-semibold" style={{color:'var(--wb-text)'}}>方法索引</div><div className="mt-0.5 text-[10px]" style={{color:'var(--wb-text-3)'}}>模块 → 题型 → 方法</div></div><button onClick={()=>setDirectoryOpen(false)} className="xl:hidden rounded-[7px] p-1.5" style={{color:'var(--wb-text-2)'}}><X className="h-4 w-4"/></button></div><div className="relative mt-3"><Search className="absolute left-3 top-2.5 h-3.5 w-3.5" style={{color:'var(--wb-text-3)'}}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索方法或识别信号" className="w-full rounded-[8px] border py-2 pl-8 pr-3 text-[11px]" style={{background:'var(--wb-surface)',borderColor:'var(--wb-border)',color:'var(--wb-text)'}}/></div></div>
    <div className="border-b p-2" style={{borderColor:'var(--wb-border)'}}><div className="flex gap-1 overflow-x-auto">{directory.map(group=><button key={group.name} onClick={()=>chooseModule(group.name)} className="whitespace-nowrap rounded-[6px] px-2 py-1.5 text-[10px] font-medium" style={{background:module===group.name?'var(--wb-accent-soft)':'transparent',color:module===group.name?'var(--wb-accent-text)':'var(--wb-text-2)'}}>{tZen(group.name,zenMode)} <span style={{color:'var(--wb-text-3)'}}>{group.count}</span></button>)}</div><div className="mt-1 flex flex-wrap gap-1">{categories.map(cat=><button key={cat.name} onClick={()=>chooseCategory(cat.name)} className="rounded-[6px] px-2 py-1 text-[9px]" style={{background:category===cat.name?'var(--wb-surface)':'transparent',color:category===cat.name?'var(--wb-text)':'var(--wb-text-3)',border:category===cat.name?'1px solid var(--wb-border)':'1px solid transparent'}}>{cat.name}</button>)}</div></div>
    <div className="flex items-center gap-1 border-b px-2 py-1.5" style={{borderColor:'var(--wb-border)'}}>{filters.map(f=><button key={f.id} onClick={()=>setFilter(f.id)} className="rounded-[6px] px-2 py-1 text-[9px] font-medium" style={{background:filter===f.id?'var(--wb-surface-hover)':'transparent',color:filter===f.id?'var(--wb-text)':'var(--wb-text-3)'}}>{f.label}</button>)}</div>
    <div className="min-h-0 flex-1 overflow-y-auto p-2"><div className="mb-1 px-2 text-[9px]" style={{color:'var(--wb-text-3)'}}>{list.length} 个方法</div>{list.map(m=><button key={m.id} onClick={()=>chooseMethod(m.id)} className="mb-0.5 flex w-full items-center gap-2 rounded-[8px] px-2.5 py-2 text-left" style={{background:selectedId===m.id?'var(--wb-accent-soft)':'transparent',color:selectedId===m.id?'var(--wb-accent-text)':'var(--wb-text-2)'}}><div className="min-w-0 flex-1"><div className="truncate text-[11px] font-medium">{m.title}</div><div className="mt-0.5 truncate font-mono text-[8px]" style={{color:'var(--wb-text-3)'}}>{m.id}</div></div>{selectedId===m.id&&<span className="h-1.5 w-1.5 rounded-full" style={{background:'var(--wb-accent)'}}/>}</button>)}</div>
  </div>;

  return <WorkspacePage id="view-methods" className="methods-one-screen !p-0 lg:h-[calc(100vh-57px)] lg:overflow-hidden">
    {directoryOpen&&<><button aria-label="关闭方法目录" onClick={()=>setDirectoryOpen(false)} className="fixed inset-0 z-40 bg-black/35 xl:hidden"/><aside className="fixed bottom-0 left-0 top-0 z-50 w-[min(320px,88vw)] shadow-2xl xl:hidden">{directoryPanel}</aside></>}
    <div className="grid min-h-full lg:h-full xl:grid-cols-[250px_390px_minmax(0,1fr)]">
      <aside className="hidden min-h-0 border-r xl:block" style={{borderColor:'var(--wb-border)'}}>{directoryPanel}</aside>

      <section className="flex min-w-0 flex-col border-r" style={{background:'var(--wb-surface)',borderColor:'var(--wb-border)'}}>
        <div className="flex shrink-0 items-center justify-between gap-2 border-b px-4 py-2.5" style={{background:'var(--wb-surface-subtle)',borderColor:'var(--wb-border)'}}><div className="flex min-w-0 items-center gap-2"><button onClick={()=>setDirectoryOpen(true)} className="xl:hidden" style={{color:'var(--wb-text-2)'}}><Menu className="h-4 w-4"/></button><span className="rounded-[5px] px-1.5 py-0.5 font-mono text-[9px]" style={{background:'var(--wb-surface-hover)',color:'var(--wb-text-3)'}}>{current.id}</span><span className="truncate text-[10px]" style={{color:'var(--wb-text-3)'}}>{current.module} · {current.category}</span></div><CopyButton text={copyCurrent} label="复制方法"/></div>
        <div className="min-h-0 flex-1 overflow-y-auto p-5"><h1 className="text-[24px] font-semibold leading-tight tracking-[-0.035em]" style={{color:'var(--wb-text)'}}>{current.title}</h1><p className="mt-2 text-[12px] leading-6" style={{color:'var(--wb-text-2)'}}>{current.definition}</p>
          <div className="mt-5 rounded-[9px] border p-4" style={{background:'var(--wb-accent-soft)',borderColor:'color-mix(in srgb,var(--wb-accent) 22%,var(--wb-border))'}}><div className="text-[9px] font-semibold uppercase tracking-[0.08em]" style={{color:'var(--wb-accent-text)'}}>考场调用口令</div><div className="mt-2 text-[17px] font-semibold leading-7" style={{color:'var(--wb-text)'}}>{current.exam_command||'暂无固定口令，按识别信号进入执行链。'}</div></div>
          <div className="mt-5"><div className="mb-2 flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-[0.06em]" style={{color:'var(--wb-text-3)'}}><Lightbulb className="h-3.5 w-3.5"/>什么时候该想到它</div><div className="flex flex-wrap gap-1.5">{current.signals.length?current.signals.map((s,i)=><span key={i} className="rounded-[6px] border px-2 py-1 text-[10px] leading-4" style={{background:'var(--wb-surface-subtle)',borderColor:'var(--wb-border)',color:'var(--wb-text-2)'}}>{s}</span>):<span className="text-[10px]" style={{color:'var(--wb-text-3)'}}>暂无识别信号</span>}</div></div>
          <div className="mt-5 border-t pt-4" style={{borderColor:'var(--wb-border)'}}><div className="mb-3 flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-[0.06em]" style={{color:'var(--wb-text-3)'}}><Route className="h-3.5 w-3.5"/>考场执行顺序</div><div className="space-y-1">{current.steps.length?current.steps.map((s,i)=><div key={i} className="grid grid-cols-[22px_minmax(0,1fr)] gap-2 rounded-[7px] px-2 py-2" style={{background:i%2===0?'var(--wb-surface-subtle)':'transparent'}}><span className="flex h-5 w-5 items-center justify-center rounded-full text-[9px] font-semibold text-white" style={{background:'var(--wb-accent)'}}>{i+1}</span><div className="text-[11px] leading-5" style={{color:'var(--wb-text-2)'}}>{s}</div></div>):<div className="text-[10px]" style={{color:'var(--wb-text-3)'}}>暂无执行步骤</div>}</div></div>
        </div>
        <div className="shrink-0 border-t p-3" style={{borderColor:'var(--wb-border)',background:'var(--wb-surface-subtle)'}}><PrimaryButton onClick={()=>window.dispatchEvent(new CustomEvent('gongkao:start-practice',{detail:{node_slug:current.node_slug||null,title:`${current.title} · 方法验证`,limit:5,estimated_minutes:8,force:false}}))} className="w-full"><Compass className="h-4 w-4"/>练 5 题验证</PrimaryButton></div>
      </section>

      <section className="flex min-w-0 flex-col" style={{background:'var(--wb-surface)'}}>
        <div className="flex shrink-0 items-center gap-1 border-b px-3 py-2" style={{background:'var(--wb-surface-subtle)',borderColor:'var(--wb-border)'}}>{detailTabs.map(tab=>{const Icon=tab.icon;return <button key={tab.id} onClick={()=>setDetailTab(tab.id)} className="inline-flex items-center gap-1.5 rounded-[7px] px-3 py-1.5 text-[10px] font-medium" style={{background:detailTab===tab.id?'var(--wb-surface)':'transparent',color:detailTab===tab.id?'var(--wb-text)':'var(--wb-text-3)',border:detailTab===tab.id?'1px solid var(--wb-border)':'1px solid transparent',boxShadow:detailTab===tab.id?'var(--wb-shadow-sm)':'none'}}><Icon className="h-3.5 w-3.5"/>{tab.label}</button>})}</div>
        <div className="min-h-0 flex-1 overflow-y-auto px-6 py-6 lg:px-8"><div className="mx-auto max-w-[780px]"><div className="mb-4 text-[10px] font-semibold uppercase tracking-[0.08em]" style={{color:'var(--wb-text-3)'}}>{detailTabs.find(t=>t.id===detailTab)?.label}</div><div className="whitespace-pre-wrap text-[14px] leading-8" style={{color:'var(--wb-text)'}}>{detailText}</div></div></div>
        <div className="shrink-0 border-t px-5 py-2.5" style={{borderColor:'var(--wb-border)',background:'var(--wb-surface-subtle)'}}><div className="flex items-center justify-between gap-3"><span className="text-[9px]" style={{color:'var(--wb-text-3)'}}>左侧负责调用与执行，右侧只放解释、例题、边界和来源。</span><span className="text-[9px] font-medium" style={{color:'var(--wb-accent-text)'}}>方法工作台</span></div></div>
      </section>
    </div>
  </WorkspacePage>;
};
