import React,{useState} from 'react';
import {BookOpen,Check,CheckCircle2,Copy,FileText,PenTool,Sparkles,Tag} from 'lucide-react';
import {useApp} from '../../context/AppContext';
import {CopyButton} from '../common/CopyButton';
import {copyText,formatGuideText} from '../../utils/copy';
import {tZen} from '../../utils/zen';

export const ShenlunView:React.FC=()=>{
  const{zenMode}=useApp();const[active,setActive]=useState('general');const[draft,setDraft]=useState('');const[copied,setCopied]=useState<string|null>(null);
  const modules=[{id:'general',name:'概括归纳',icon:BookOpen},{id:'analysis',name:'综合分析',icon:Sparkles},{id:'policy',name:'提出对策',icon:CheckCircle2},{id:'official',name:'贯彻执行(公文)',icon:FileText},{id:'essay',name:'申论大作文',icon:PenTool}];
  const vocab=[{category:'组织领导与体制机制',words:['压紧压实责任链条','破除部门职能壁垒','健全闭环问效机制','强化跨部门协同联动','完善常态化督导巡查','优化考评指标体系']},{category:'产业发展与实体经济',words:['加快数智赋能转型','拉长拓宽产业链条','构筑特色品牌矩阵','激发专精特新活力','打造协同创新集聚区','推动要素高效配置']},{category:'基层治理与为民服务',words:['推动治理重心下移','畅通诉求表达直通车','实现矛盾源头化解','提升精细化治理效能','构建一站式便民服务','健全多元共治新格局']},{category:'文化赋能与宣传引导',words:['厚植本土特色文脉','创新沉浸式传播形态','注重先进典型引领','凝聚社会广泛共识','激活传统文化生命力','以文化软实力赋能经济']}];
  const guides:Record<string,{title:string;steps:string[];formula:string}>={general:{title:'单一归纳概括题作答法则',steps:['审题定位作答对象（问题、原因、经验、举措、特点、成效等）','带着对象精读材料，在材料中勾画核心主谓宾及动宾短语','同类合并归纳，提炼4-6个前置规范词小标题','采用“总括句 + 规范词 + 展开表述”格式成文'],formula:'总括句 + 一是【规范词小标题】+ 具体要点展开；二是【规范词小标题】+ 具体要点展开...'},analysis:{title:'综合分析（词句理解/评价型）作答法则',steps:['点明本质：解释词句含义或给出明确态度倾向','展开论证：结合材料剖析原因、背景、现状、意义与风险','得出结论/对策：简明提出化解矛盾或深化落实的措施'],formula:'【表态/释义】+ 【分析原因/影响/危害】+ 【落实/应对对策】三段论'},policy:{title:'提出对策题作答法则',steps:['反推问题：每个具体痛点都应有对应对策','主体明确：明确政府、企业、协会、公众等实施主体','对策四要素：主体 + 对象 + 方式/手段 + 预期目的','针对性与可行性优先，避免空泛口号'],formula:'对策结构 = 主体 + 动作规范词 + 客体 + 落地手段 + 达成效果'},official:{title:'贯彻执行与法定公文作答法则',steps:['五要素审题：文种、发文主体、受文对象、行文目的、格式要求','按文种确定标题、称谓、正文、落款和日期是否需要','正文核心要点仍按材料踩点，语言风格匹配文体'],formula:'标题 + 称谓 + 开头交代背景 + 核心要点分类列项 + 结语 + 必要的署名日期'},essay:{title:'申论大作文（议论文）结构法则',steps:['准确定位中心总论点：立足全篇材料主题','设置3个有区分度且支撑总论点的分论点','开篇破题—分论点展开—结尾回扣升华，论证必须使用材料与可解释事实'],formula:'标题 + 引论 + 分论点论证 + 结论；结构服务论证，不机械套模板'}};
  const g=guides[active];const copy=async(w:string)=>{if(await copyText(w)){setCopied(w);setTimeout(()=>setCopied(null),1600)}};
  return <div id="view-shenlun" className="p-4 md:p-8 max-w-6xl mx-auto space-y-6"><div><h2 className="text-xl font-bold text-stone-900 tracking-tight">{tZen('申论作答规范与机关语料库',zenMode)}</h2><p className="text-xs text-stone-600 mt-1">坚持材料为王、踩点给分、规范表达。</p></div><div className="flex items-center gap-2 border-b border-stone-200 pb-3 overflow-x-auto text-xs">{modules.map(m=>{const Icon=m.icon,on=active===m.id;return <button key={m.id} onClick={()=>setActive(m.id)} className={`px-3.5 py-2 rounded-xl font-semibold transition-all flex items-center gap-1.5 whitespace-nowrap ${on?'bg-stone-900 text-white shadow-2xs':'bg-stone-100 text-stone-700 hover:bg-stone-200'}`}><Icon className="w-3.5 h-3.5"/>{tZen(m.name,zenMode)}</button>})}</div>
    <div className="p-6 rounded-2xl bg-white border border-stone-200 shadow-2xs space-y-4"><div className="flex items-center justify-between gap-4 border-b border-stone-100 pb-3"><h3 className="text-sm font-bold text-stone-900">{g.title}</h3><CopyButton text={formatGuideText(g.title,g.steps,g.formula)} label="复制方法"/></div><div className="space-y-2 text-xs text-stone-800 leading-relaxed"><div className="font-semibold text-stone-900">核心作答动作：</div><ol className="list-decimal list-inside space-y-1 text-stone-700 pl-1">{g.steps.map((s,i)=><li key={i}>{s}</li>)}</ol></div><div className="p-3.5 rounded-xl bg-amber-50/70 border border-amber-200 text-xs text-amber-950 font-mono space-y-1"><div className="font-bold flex items-center gap-1"><Sparkles className="w-3.5 h-3.5 text-amber-700"/>推荐答题结构：</div><div className="leading-relaxed opacity-95">{g.formula}</div></div></div>
    <div className="p-6 rounded-2xl bg-white border border-stone-200 shadow-2xs space-y-4"><div className="flex items-center justify-between border-b border-stone-100 pb-3"><div className="flex items-center gap-2"><Tag className="w-4 h-4 text-stone-600"/><h3 className="text-sm font-bold text-stone-900">申论机关规范表达词库（点击复制）</h3></div>{copied&&<span className="text-xs text-emerald-700 font-semibold flex items-center gap-1"><Check className="w-3.5 h-3.5"/>已复制：“{copied}”</span>}</div><div className="grid grid-cols-1 md:grid-cols-2 gap-4">{vocab.map(v=><div key={v.category} className="p-4 rounded-xl bg-stone-50/80 border border-stone-200/80 space-y-2.5 text-xs"><div className="font-semibold text-stone-900 text-xs">{v.category}</div><div className="flex flex-wrap gap-1.5">{v.words.map(w=><button key={w} onClick={()=>void copy(w)} className="px-2.5 py-1 rounded-lg bg-white hover:bg-stone-200 border border-stone-200 text-stone-800 text-[11px] transition-colors flex items-center gap-1 group shadow-2xs"><span>{w}</span><Copy className="w-2.5 h-2.5 text-stone-400"/></button>)}</div></div>)}</div></div>
    <div className="p-6 rounded-2xl bg-white border border-stone-200 shadow-2xs space-y-4"><div className="flex items-center justify-between border-b border-stone-100 pb-3"><div className="flex items-center gap-2"><PenTool className="w-4 h-4 text-stone-600"/><h3 className="text-sm font-bold text-stone-900">申论作答草稿演练台</h3></div><span className="text-xs font-mono text-stone-600">当前字数: <strong className={`text-sm ${draft.length>1000?'text-rose-600':'text-stone-900'}`}>{draft.length}</strong> 字</span></div><textarea rows={7} value={draft} onChange={e=>setDraft(e.target.value)} placeholder="在此处练习作答..." className="w-full p-4 border border-stone-300 rounded-xl text-xs font-mono leading-relaxed"/><div className="flex justify-between items-center text-xs text-stone-600"><span>练习完成后核对要点是否来自材料、层次是否清楚</span><button onClick={()=>setDraft('')} className="hover:text-stone-900">清空草稿</button></div></div>
  </div>;
};
