import React,{useState} from 'react';
import {BookOpen,Check,CheckCircle2,Copy,FileText,PenTool,Sparkles,Tag,ArrowRight} from 'lucide-react';
import {useApp} from '../../context/AppContext';
import {CopyButton} from '../common/CopyButton';
import {copyText,formatGuideText} from '../../utils/copy';
import {tZen} from '../../utils/zen';
import {WorkspacePage,HeroPanel,Surface,SectionHeader,Segmented} from '../common/WorkspaceUi';

export const ShenlunView:React.FC=()=>{
  const{zenMode}=useApp();const[active,setActive]=useState('general');const[draft,setDraft]=useState('');const[copied,setCopied]=useState<string|null>(null);
  const modules=[{id:'general',name:'概括归纳',icon:BookOpen},{id:'analysis',name:'综合分析',icon:Sparkles},{id:'policy',name:'提出对策',icon:CheckCircle2},{id:'official',name:'贯彻执行(公文)',icon:FileText},{id:'essay',name:'申论大作文',icon:PenTool}];
  const vocab=[{category:'组织领导与体制机制',words:['压紧压实责任链条','破除部门职能壁垒','健全闭环问效机制','强化跨部门协同联动','完善常态化督导巡查','优化考评指标体系']},{category:'产业发展与实体经济',words:['加快数智赋能转型','拉长拓宽产业链条','构筑特色品牌矩阵','激发专精特新活力','打造协同创新集聚区','推动要素高效配置']},{category:'基层治理与为民服务',words:['推动治理重心下移','畅通诉求表达直通车','实现矛盾源头化解','提升精细化治理效能','构建一站式便民服务','健全多元共治新格局']},{category:'文化赋能与宣传引导',words:['厚植本土特色文脉','创新沉浸式传播形态','注重先进典型引领','凝聚社会广泛共识','激活传统文化生命力','以文化软实力赋能经济']}];
  const guides:Record<string,{title:string;steps:string[];formula:string}>={general:{title:'单一归纳概括题作答法则',steps:['审题定位作答对象（问题、原因、经验、举措、特点、成效等）','带着对象精读材料，在材料中勾画核心主谓宾及动宾短语','同类合并归纳，提炼4-6个前置规范词小标题','采用“总括句 + 规范词 + 展开表述”格式成文'],formula:'总括句 + 一是【规范词小标题】+ 具体要点展开；二是【规范词小标题】+ 具体要点展开...'},analysis:{title:'综合分析（词句理解/评价型）作答法则',steps:['点明本质：解释词句含义或给出明确态度倾向','展开论证：结合材料剖析原因、背景、现状、意义与风险','得出结论/对策：简明提出化解矛盾或深化落实的措施'],formula:'【表态/释义】+ 【分析原因/影响/危害】+ 【落实/应对对策】三段论'},policy:{title:'提出对策题作答法则',steps:['反推问题：每个具体痛点都应有对应对策','主体明确：明确政府、企业、协会、公众等实施主体','对策四要素：主体 + 对象 + 方式/手段 + 预期目的','针对性与可行性优先，避免空泛口号'],formula:'对策结构 = 主体 + 动作规范词 + 客体 + 落地手段 + 达成效果'},official:{title:'贯彻执行与法定公文作答法则',steps:['五要素审题：文种、发文主体、受文对象、行文目的、格式要求','按文种确定标题、称谓、正文、落款和日期是否需要','正文核心要点仍按材料踩点，语言风格匹配文体'],formula:'标题 + 称谓 + 开头交代背景 + 核心要点分类列项 + 结语 + 必要的署名日期'},essay:{title:'申论大作文（议论文）结构法则',steps:['准确定位中心总论点：立足全篇材料主题','设置3个有区分度且支撑总论点的分论点','开篇破题—分论点展开—结尾回扣升华，论证必须使用材料与可解释事实'],formula:'标题 + 引论 + 分论点论证 + 结论；结构服务论证，不机械套模板'}};
  const g=guides[active];const copy=async(w:string)=>{if(await copyText(w)){setCopied(w);setTimeout(()=>setCopied(null),1600)}};
  return <WorkspacePage id="view-shenlun" className="space-y-5"><HeroPanel tone="warm"><div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-end"><div><div className="text-[10px] font-semibold tracking-[0.16em] text-[#96721c]">SHENLUN WORKBENCH</div><h1 className="mt-2 text-3xl font-bold tracking-[-0.04em] text-[#202124]">{tZen('申论作答规范与语料',zenMode)}</h1><p className="mt-2 max-w-2xl text-xs leading-6 text-[#73787f]">方法、规范表达和草稿演练放在一张工作台里；不做知识卡片墙，直接围绕“怎么写”组织。</p></div><Segmented items={modules.map(m=>({id:m.id,label:tZen(m.name,zenMode)}))} value={active} onChange={setActive}/></div></HeroPanel>
<div className="grid gap-5 xl:grid-cols-[minmax(0,1.25fr)_minmax(360px,.75fr)]"><div className="space-y-5"><Surface tone="blue" pad="lg"><SectionHeader title={g.title} subtitle="先按动作顺序组织材料，再套结构；结构服务踩点，不替代材料。" action={<CopyButton text={formatGuideText(g.title,g.steps,g.formula)} label="复制方法"/>}/><div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_260px]"><div className="space-y-2">{g.steps.map((s,i)=><div key={i} className="flex gap-3 rounded-[18px] bg-white/72 px-4 py-3 ring-1 ring-black/[0.035]"><span className="flex h-7 w-7 flex-shrink-0 items-center justify-center rounded-full bg-[#202124] text-[10px] font-bold text-white">{i+1}</span><div className="pt-0.5 text-[12px] leading-6 text-[#555a60]">{s}</div></div>)}</div><div className="rounded-[22px] bg-[#fff7dc] p-4 ring-1 ring-[#ecdfb4]"><div className="flex items-center gap-1.5 text-[10px] font-bold text-[#8a6812]"><Sparkles className="h-3.5 w-3.5"/>推荐答题结构</div><div className="mt-3 text-[12px] font-semibold leading-6 text-[#5a523f]">{g.formula}</div></div></div></Surface>
<Surface pad="lg"><SectionHeader title="机关规范表达词库" subtitle="点击直接复制，按功能分组，不要求逐条背诵。" action={<Tag className="h-4 w-4 text-[#6870b7]"/>}/>{copied&&<div className="mb-3 inline-flex items-center gap-1 rounded-full bg-[#e9f7ef] px-2.5 py-1 text-[9px] font-semibold text-[#34765b]"><Check className="h-3 w-3"/>已复制：{copied}</div>}<div className="grid gap-4 md:grid-cols-2">{vocab.map(v=><div key={v.category}><div className="mb-2 text-[10px] font-bold text-[#53585d]">{v.category}</div><div className="flex flex-wrap gap-2">{v.words.map(w=><button key={w} onClick={()=>void copy(w)} className="group inline-flex items-center gap-1.5 rounded-full bg-[#f5f7fa] px-3 py-2 text-[10px] font-medium text-[#5f646a] ring-1 ring-black/[0.035] hover:bg-white hover:text-[#202124] hover:shadow-sm"><span>{w}</span><Copy className="h-2.5 w-2.5 text-[#9aa0a6]"/></button>)}</div></div>)}</div></Surface></div>
<aside className="space-y-5"><Surface tone="violet" pad="lg" className="xl:sticky xl:top-4"><SectionHeader title="作答草稿演练" subtitle="把当前方法立刻写一遍，关注结构和踩点，而不是润色。" action={<PenTool className="h-4 w-4 text-[#7062b9]"/>}/><div className="flex items-center justify-between rounded-[16px] bg-white/65 px-3 py-2 text-[9px]"><span className="text-[#8b9096]">当前字数</span><strong className={`font-mono text-sm ${draft.length>1000?'text-[#a14e69]':'text-[#303134]'}`}>{draft.length}</strong></div><textarea rows={18} value={draft} onChange={e=>setDraft(e.target.value)} placeholder="在此处练习作答..." className="mt-3 w-full resize-y rounded-[18px] bg-white/82 p-4 text-[12px] leading-7 text-[#44484d] outline-none ring-1 ring-black/[0.055] focus:ring-[#bac5ed]"/><div className="mt-3 flex items-center justify-between text-[9px] text-[#8a9096]"><span>核对：要点来自材料 · 层次清楚</span><button onClick={()=>setDraft('')} className="font-semibold text-[#767b82]">清空</button></div></Surface><Surface tone="green" pad="lg"><SectionHeader title="当前动作"/><button className="inline-flex items-center gap-1 text-[11px] font-semibold text-[#34765b]">按本题型结构写一遍<ArrowRight className="h-3.5 w-3.5"/></button></Surface></aside></div></WorkspacePage>;
};
