import React,{useEffect,useMemo,useState} from 'react';
import {BarChart3,Clock3,Flame,Play,RefreshCw,Activity,CalendarRange} from 'lucide-react';
import {useApp} from '../../context/AppContext';
import {tZen} from '../../utils/zen';
import {WorkspacePage,HeroPanel,MetricRail,Metric,Surface,SectionHeader,PrimaryButton,QuietButton} from '../common/WorkspaceUi';

type Dist={label:string;sessions?:number;duration_sec?:number;share?:number};
type StudyData={summary?:{total_sec?:number;week_sec?:number;today_sec?:number;deep_sec?:number;deep_ratio?:number;session_count?:number;active_days?:number;avg_session_sec?:number;longest_session_sec?:number};daily?:Array<{study_date:string;duration_sec?:number;deep_sec?:number;focus_sec?:number;fragment_sec?:number}>;module?:Dist[];activity?:Dist[];time_slot?:Dist[];heatmap?:Array<{date:string;seconds:number;weekday:number}>;sessions?:Array<{id:number;study_date:string;start_at?:string;duration_sec?:number;module?:string;activity_type?:string;category?:string}>};
const fmt=(sec=0)=>sec>=3600?`${(sec/3600).toFixed(1)}h`:`${Math.round(sec/60)}m`;
const pct=(n=0)=>`${Math.round(n*100)}%`;

export const StudyAnalyticsView:React.FC=()=>{const{startTimer,zenMode}=useApp();const[data,setData]=useState<StudyData>({});const[loading,setLoading]=useState(true);const[error,setError]=useState('');const load=()=>{setLoading(true);setError('');fetch('/api/analytics/study?days=90').then(async r=>{if(!r.ok){let msg=`HTTP ${r.status}`;try{const p=await r.json();msg=p?.error?.message||p?.detail||msg}catch{}throw new Error(msg)}return r.json()}).then(p=>setData(p&&typeof p==='object'?p:{})).catch(e=>setError(e?.message||'学习投入数据读取失败')).finally(()=>setLoading(false))};useEffect(load,[]);const s=data.summary||{};const daily=Array.isArray(data.daily)?data.daily.slice(-30):[];const maxDay=Math.max(1,...daily.map(x=>Number(x.duration_sec||0)));const heat=Array.isArray(data.heatmap)?data.heatmap.slice(-70):[];const dist=useMemo(()=>({module:Array.isArray(data.module)?data.module:[],activity:Array.isArray(data.activity)?data.activity:[],time:Array.isArray(data.time_slot)?data.time_slot:[]}),[data]);if(loading)return <div className="p-12 text-center text-sm text-[#858a90]">正在读取学习投入数据…</div>;
return <WorkspacePage id="view-study-analytics" className="space-y-5"><HeroPanel tone="blue"><div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(460px,.85fr)] lg:items-end"><div><div className="text-[10px] font-semibold tracking-[0.16em] text-[#6574bb]">STUDY INPUT · 90 DAYS</div><h1 className="mt-2 text-3xl font-bold tracking-[-0.04em] text-[#202124]">{tZen('学习投入看板',zenMode)}</h1><p className="mt-2 max-w-2xl text-xs leading-6 text-[#73787f]">重点不是“学了多久”，而是学习是否持续、是否进入深度状态，以及时间最终流向了哪些模块。</p><div className="mt-5 flex flex-wrap gap-2"><PrimaryButton onClick={()=>void startTimer('资料分析','真题训练','pomodoro',1500)}><Play className="h-3.5 w-3.5"/>开始 25 分钟</PrimaryButton><QuietButton onClick={load}><RefreshCw className="h-3.5 w-3.5"/>刷新</QuietButton></div></div><div className="rounded-[22px] bg-white/64 p-4 ring-1 ring-black/[0.04]"><MetricRail columns="grid-cols-4"><Metric compact label="90 日累计" value={fmt(Number(s.total_sec||0))}/><Metric compact label="本周" value={fmt(Number(s.week_sec||0))}/><Metric compact label="今日" value={fmt(Number(s.today_sec||0))}/><Metric compact label="深度占比" value={pct(Number(s.deep_ratio||0))} accent="text-[#5f6bbb]"/></MetricRail></div></div></HeroPanel>{error&&<div className="rounded-[18px] bg-[#fff0f3] px-4 py-3 text-xs text-[#a24d68] ring-1 ring-[#efd7df]">{error}</div>}
<div className="grid gap-5 xl:grid-cols-[minmax(0,1.6fr)_minmax(320px,.6fr)]"><Surface pad="lg"><SectionHeader title="近 30 日学习节奏" subtitle="柱体总高代表有效投入，深色部分代表深度学习。" action={<Activity className="h-4 w-4 text-[#6571bb]"/>}/><div className="h-64 flex items-end gap-1.5">{daily.length?daily.map(d=>{const total=Number(d.duration_sec||0),deep=Number(d.deep_sec||0),height=Math.max(total?5:1,total/maxDay*100),deepShare=total?deep/total*100:0;return <div key={d.study_date} title={`${d.study_date} · ${fmt(total)}`} className="group flex h-full flex-1 items-end"><div className="relative w-full overflow-hidden rounded-t-[7px] bg-[#e9edf3] transition-all group-hover:bg-[#dfe4ec]" style={{height:`${height}%`}}>{total>0&&<div className="absolute bottom-0 w-full bg-[linear-gradient(180deg,#6e7bc9,#3e465e)]" style={{height:`${deepShare}%`}}/>}</div></div>}):<div className="m-auto text-xs text-[#9aa0a6]">暂无学习记录</div>}</div><div className="mt-3 flex justify-between text-[9px] text-[#9aa0a6]"><span>30 天前</span><span>今天</span></div></Surface><aside className="space-y-5"><Surface tone="green" pad="lg"><SectionHeader title="投入质量" action={<Flame className="h-4 w-4 text-[#3c8465]"/>}/><div className="space-y-3">{[["有效次数",`${Number(s.session_count||0)} 次`],["活跃天数",`${Number(s.active_days||0)} 天`],["平均单次",fmt(Number(s.avg_session_sec||0))],["最长单次",fmt(Number(s.longest_session_sec||0))]].map(([a,b])=><div key={a} className="flex items-center justify-between rounded-[15px] bg-white/65 px-3 py-2.5"><span className="text-[10px] text-[#7e848a]">{a}</span><strong className="font-mono text-[12px] text-[#303134]">{b}</strong></div>)}</div></Surface><Surface tone="violet" pad="lg"><SectionHeader title="投入判断"/><div className="space-y-3 text-[11px] leading-5 text-[#676c72]"><p><b className="text-[#41454a]">活跃天数</b> 看连续性。</p><p><b className="text-[#41454a]">平均单次</b> 看是否容易碎片化。</p><p><b className="text-[#41454a]">深度占比</b> 看高质量训练是否真正发生。</p></div></Surface></aside></div>
<Surface pad="lg"><SectionHeader title="近 70 日活跃热力" subtitle="颜色越深代表当天有效学习时长越高。" action={<CalendarRange className="h-4 w-4 text-[#6b72b8]"/>}/><div className="grid grid-cols-10 gap-1.5 sm:grid-cols-14 xl:grid-cols-20">{heat.length?heat.map(x=>{const mins=Math.round(Number(x.seconds||0)/60);const cls=mins>=90?'bg-[#3c4358]':mins>=45?'bg-[#7883b8]':mins>=15?'bg-[#cbd2e8]':'bg-[#eceff4]';return <div key={x.date} title={`${x.date} · ${mins}分钟`} className={`aspect-square rounded-[5px] ${cls}`}/>}):<span className="text-xs text-[#9aa0a6]">暂无数据</span>}</div></Surface>
<div className="grid gap-5 lg:grid-cols-3">{([['模块分布',dist.module],['活动分布',dist.activity],['时段分布',dist.time]] as [string,Dist[]][]).map(([title,rows],idx)=><Surface key={title} tone={idx===0?'blue':idx===1?'warm':'plain'} pad="lg"><SectionHeader title={title}/><div className="space-y-3">{rows.length?rows.slice(0,8).map((x,i)=><div key={`${x.label}-${i}`}><div className="mb-1.5 flex justify-between gap-3 text-[10px]"><span className="truncate font-medium text-[#62676d]">{x.label||'未分类'}</span><span className="font-mono text-[#8c9198]">{fmt(Number(x.duration_sec||0))} · {pct(Number(x.share||0))}</span></div><div className="h-2 overflow-hidden rounded-full bg-white/65"><div className="h-full rounded-full bg-[linear-gradient(90deg,#6f7bd5,#9b79cb)]" style={{width:`${Math.max(2,Number(x.share||0)*100)}%`}}/></div></div>):<div className="text-xs text-[#9aa0a6]">暂无数据</div>}</div></Surface>)}</div></WorkspacePage>}
