import React,{useEffect,useMemo,useState} from 'react';
import {ArrowRight,CheckCircle2,Play,Search,XCircle} from 'lucide-react';
import {useApp} from '../../context/AppContext';
import {CopyButton} from '../common/CopyButton';
import {formatQuestionText} from '../../utils/copy';
import {tZen} from '../../utils/zen';

type SetRow={id:string;title:string;bank_ids:number[];count:number;estimated_minutes:number;reason:string};
type Active={active?:boolean;session_id?:string;title?:string;questions?:any[];current_index?:number;remaining_sec?:number;answers?:Record<string,any>};

export const TrainingsView:React.FC=()=>{
  const{trainings,questions,setSelectedQuestionId,zenMode}=useApp();const[tab,setTab]=useState<'recommended'|'bank'|'history'>('recommended');const[sets,setSets]=useState<SetRow[]>([]);const[active,setActive]=useState<Active|null>(null);const[q,setQ]=useState('');const[module,setModule]=useState('all');const[correct,setCorrect]=useState<'all'|'correct'|'incorrect'>('all');const[selected,setSelected]=useState<number[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
  const modules=Array.from(new Set(questions.map(x=>x.module))).filter(Boolean);
  const load=()=>{setLoading(true);Promise.all([fetch('/api/v2/practice/recommendations').then(r=>r.ok?r.json():[]),fetch('/api/v2/practice/state').then(r=>r.ok?r.json():null)]).then(([a,b])=>{setSets(Array.isArray(a)?a:[]);setActive(b?.session_id?b:null)}).catch(()=>{}).finally(()=>setLoading(false))};
  useEffect(load,[]);useEffect(()=>{const fn=()=>load();window.addEventListener('gongkao:practice-finished',fn);return()=>window.removeEventListener('gongkao:practice-finished',fn)},[]);
  const start=(detail:any)=>window.dispatchEvent(new CustomEvent('gongkao:start-practice',{detail}));const resume=()=>window.dispatchEvent(new CustomEvent('gongkao:resume-practice'));
  const filtered=useMemo(()=>questions.filter(x=>(module==='all'||x.module===module)&&(correct==='all'||(correct==='correct'?x.isCorrect===true:x.isCorrect===false))&&(!q.trim()||`${x.stem}\n${x.subType}\n${x.errorPattern||''}`.toLowerCase().includes(q.toLowerCase()))),[questions,module,correct,q]);
  const toggle=(id:number)=>setSelected(p=>p.includes(id)?p.filter(x=>x!==id):[...p,id]);const bankIds=selected.map(id=>questions.find(x=>x.id===id)?.bankId).filter((x):x is number=>!!x);
  return <div id="view-trainings" className="p-4 md:p-8 max-w-6xl mx-auto space-y-5"><div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4"><div><h2 className="text-xl font-bold text-stone-900 tracking-tight">{tZen('训练与真实题库',zenMode)}</h2><p className="text-xs text-stone-600 mt-1">你决定“刷题”，系统负责把当前最值得做的题组排在前面。</p></div><div className="flex border-b border-stone-300 text-xs"><button onClick={()=>setTab('recommended')} className={`px-3 py-2 ${tab==='recommended'?'border-b-2 border-stone-900 font-semibold':'text-stone-500'}`}>推荐训练</button><button onClick={()=>setTab('bank')} className={`px-3 py-2 ${tab==='bank'?'border-b-2 border-stone-900 font-semibold':'text-stone-500'}`}>自选题目</button><button onClick={()=>setTab('history')} className={`px-3 py-2 ${tab==='history'?'border-b-2 border-stone-900 font-semibold':'text-stone-500'}`}>训练记录</button></div></div>
    {active&&<button onClick={resume} className="w-full px-4 py-3 bg-stone-900 text-white text-left flex items-center justify-between gap-3"><span className="text-sm font-semibold">继续：{active.title} · 剩 {Math.max(0,(active.questions?.length||0)-Object.keys(active.answers||{}).length)} 题 · {Math.floor(Number(active.remaining_sec||0)/60).toString().padStart(2,'0')}:{String(Number(active.remaining_sec||0)%60).padStart(2,'0')}</span><ArrowRight className="w-4 h-4"/></button>}
    {error&&<div className="py-2 text-xs text-rose-700">{error}</div>}
    {tab==='recommended'&&<section><div className="grid grid-cols-[minmax(0,1fr)_auto_auto] px-3 py-2 text-[11px] text-stone-500 border-b border-stone-300"><span>已配好的题组</span><span>预计</span><span className="w-20 text-right">开始</span></div>{loading?<div className="py-10 text-center text-xs text-stone-500">正在根据错题、复发模式和计划配题…</div>:sets.length===0?<div className="py-10 text-center text-xs text-stone-500">题库样本不足，先导入真实练习后再生成推荐题组。</div>:sets.map(row=><div key={row.id} className="grid grid-cols-[minmax(0,1fr)_auto_auto] items-center gap-4 px-3 py-3 border-b border-stone-200 bg-white"><div className="min-w-0"><div className="text-sm font-semibold text-stone-900 truncate">{row.title} · {row.count} 题</div><div className="text-[11px] text-stone-500 mt-0.5 truncate">{row.reason}</div></div><span className="text-xs font-mono text-stone-600 whitespace-nowrap">约 {row.estimated_minutes} 分钟</span><button onClick={()=>start({set_id:row.id,force:false})} className="w-20 px-3 py-1.5 bg-stone-900 text-white text-xs font-semibold inline-flex justify-center items-center gap-1"><Play className="w-3 h-3"/>开始</button></div>)}</section>}
    {tab==='bank'&&<section className="space-y-3"><div className="flex flex-wrap gap-2 items-center border-b border-stone-300 pb-3"><div className="relative flex-1 min-w-[220px]"><Search className="w-4 h-4 absolute left-2.5 top-2.5 text-stone-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索题干、题型或错误模式" className="w-full pl-8 pr-3 py-2 border border-stone-300 bg-white text-xs"/></div><select value={module} onChange={e=>setModule(e.target.value)} className="px-3 py-2 border border-stone-300 bg-white text-xs"><option value="all">全部模块</option>{modules.map(m=><option key={m}>{tZen(m,zenMode)}</option>)}</select><select value={correct} onChange={e=>setCorrect(e.target.value as any)} className="px-3 py-2 border border-stone-300 bg-white text-xs"><option value="all">全部历史状态</option><option value="correct">历史正确</option><option value="incorrect">历史错误</option></select><button disabled={!bankIds.length} onClick={()=>{if(!bankIds.length){setError('所选题目缺少题库ID，无法重新训练。');return}start({title:`自选真题 · ${bankIds.length}题`,bank_ids:bankIds,estimated_minutes:Math.max(5,Math.round(bankIds.length*1.5)),force:false})}} className="px-3 py-2 bg-stone-900 disabled:bg-stone-300 text-white text-xs font-semibold">练所选 {bankIds.length} 题</button></div><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-xs"><thead><tr className="text-left text-stone-500 border-b border-stone-300"><th className="py-2 w-10"></th><th>题型</th><th>题干</th><th>历史状态</th><th>用时</th><th className="text-right">操作</th></tr></thead><tbody>{filtered.map(x=>{const copy=formatQuestionText({id:x.id,module:x.module,subType:x.subType,stem:x.stem,options:x.options});return <tr key={x.id} className="border-b border-stone-200 hover:bg-white"><td className="py-2.5"><input type="checkbox" checked={selected.includes(x.id)} disabled={!x.bankId} onChange={()=>toggle(x.id)}/></td><td className="py-2.5 whitespace-nowrap">{tZen(x.module,zenMode)} · {x.subType}</td><td className="max-w-[440px] truncate text-stone-800">{x.stem}</td><td>{x.isCorrect===true?<span className="inline-flex items-center gap-1 text-emerald-700"><CheckCircle2 className="w-3 h-3"/>正确</span>:x.isCorrect===false?<span className="inline-flex items-center gap-1 text-rose-700"><XCircle className="w-3 h-3"/>错误</span>:'—'}</td><td className="font-mono">{x.durationSec?`${x.durationSec}s`:'—'}</td><td className="text-right whitespace-nowrap"><CopyButton text={copy} label="复制" className="mr-3"/><button onClick={()=>setSelectedQuestionId(x.id)} className="text-stone-600 hover:text-stone-950">查看</button></td></tr>})}</tbody></table></div></section>}
    {tab==='history'&&<section className="overflow-x-auto"><table className="w-full min-w-[720px] text-xs"><thead><tr className="text-left text-stone-500 border-b border-stone-300"><th className="py-2">日期</th><th>来源</th><th>题量</th><th>正确率</th><th>总用时</th><th>均速</th><th>备注</th></tr></thead><tbody>{trainings.map(tr=><tr key={tr.id} className="border-b border-stone-200"><td className="py-2.5 font-mono">{tr.date}</td><td>{tr.source}</td><td>{tr.correctQ}/{tr.totalQ}</td><td className="font-mono">{Math.round(tr.accuracy*100)}%</td><td>{tr.durationMin}m</td><td>{tr.avgSecPerQ||'—'}s</td><td className="max-w-[300px] truncate text-stone-500">{tr.note||'—'}</td></tr>)}</tbody></table></section>}
  </div>;
};
