import React,{useEffect,useMemo,useState} from 'react';
import {ArrowRight,CheckCircle2,Play,Search,XCircle,Clock3,Layers3} from 'lucide-react';
import {useApp} from '../../context/AppContext';
import {CopyButton} from '../common/CopyButton';
import {formatQuestionText} from '../../utils/copy';
import {tZen} from '../../utils/zen';
import {WorkspacePage,HeroPanel,Segmented,Surface,SectionHeader,PrimaryButton,QuietButton,EmptyState} from '../common/WorkspaceUi';

type SetRow={id:string;title:string;bank_ids:number[];count:number;estimated_minutes:number;reason:string};
type Active={active?:boolean;session_id?:string;title?:string;questions?:any[];current_index?:number;remaining_sec?:number;answers?:Record<string,any>};

export const TrainingsView:React.FC=()=>{
  const{trainings,questions,setSelectedQuestionId,zenMode}=useApp();const[tab,setTab]=useState<'recommended'|'bank'|'history'>('recommended');const[sets,setSets]=useState<SetRow[]>([]);const[active,setActive]=useState<Active|null>(null);const[q,setQ]=useState('');const[module,setModule]=useState('all');const[correct,setCorrect]=useState<'all'|'correct'|'incorrect'>('all');const[selected,setSelected]=useState<number[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
  const modules=Array.from(new Set(questions.map(x=>x.module))).filter(Boolean);
  const load=()=>{setLoading(true);Promise.all([fetch('/api/v2/practice/recommendations').then(r=>r.ok?r.json():[]),fetch('/api/v2/practice/state').then(r=>r.ok?r.json():null)]).then(([a,b])=>{setSets(Array.isArray(a)?a:[]);setActive(b?.session_id?b:null)}).catch(()=>{}).finally(()=>setLoading(false))};
  useEffect(load,[]);useEffect(()=>{const fn=()=>load();window.addEventListener('gongkao:practice-finished',fn);return()=>window.removeEventListener('gongkao:practice-finished',fn)},[]);
  const start=(detail:any)=>window.dispatchEvent(new CustomEvent('gongkao:start-practice',{detail}));const resume=()=>window.dispatchEvent(new CustomEvent('gongkao:resume-practice'));
  const filtered=useMemo(()=>questions.filter(x=>(module==='all'||x.module===module)&&(correct==='all'||(correct==='correct'?x.isCorrect===true:x.isCorrect===false))&&(!q.trim()||`${x.stem}\n${x.subType}\n${x.errorPattern||''}`.toLowerCase().includes(q.toLowerCase()))),[questions,module,correct,q]);
  const toggle=(id:number)=>setSelected(p=>p.includes(id)?p.filter(x=>x!==id):[...p,id]);const bankIds=selected.map(id=>questions.find(x=>x.id===id)?.bankId).filter((x):x is number=>!!x);
  const tabs=[{id:'recommended',label:'推荐训练'},{id:'bank',label:'自选题目'},{id:'history',label:'训练记录'}];
  const resumeLeft=Math.max(0,(active?.questions?.length||0)-Object.keys(active?.answers||{}).length);const resumeTime=Number(active?.remaining_sec||0);
  return <WorkspacePage id="view-trainings" className="space-y-5"><HeroPanel tone="blue"><div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_auto] xl:items-end"><div><div className="text-[10px] font-semibold tracking-[0.16em] text-[#6574bb]">PRACTICE ENGINE</div><h1 className="mt-2 text-3xl font-bold tracking-[-0.04em] text-[#202124]">{tZen('训练与真实题库',zenMode)}</h1><p className="mt-2 max-w-2xl text-xs leading-6 text-[#70767d]">你只决定要不要刷题；系统负责把当前最值得做的题组、到期复训和自选题库放到同一个训练入口。</p>{active&&<button onClick={resume} className="mt-5 flex w-full max-w-2xl items-center justify-between gap-4 rounded-[20px] bg-[#202124] px-4 py-3.5 text-left text-white shadow-lg"><div><div className="text-[9px] font-semibold tracking-[0.12em] text-white/55">RESUME SESSION</div><div className="mt-1 text-sm font-bold">继续：{active.title}</div><div className="mt-1 text-[10px] text-white/60">剩 {resumeLeft} 题 · {Math.floor(resumeTime/60).toString().padStart(2,'0')}:{String(resumeTime%60).padStart(2,'0')}</div></div><ArrowRight className="h-4 w-4"/></button>}</div><Segmented items={tabs} value={tab} onChange={setTab}/></div></HeroPanel>{error&&<div className="rounded-[18px] bg-[#fff0f3] px-4 py-3 text-xs text-[#a24d68] ring-1 ring-[#efd7df]">{error}</div>}
{tab==='recommended'&&<div className="grid gap-5 xl:grid-cols-[minmax(0,1.4fr)_minmax(280px,.6fr)]"><Surface pad="lg"><SectionHeader title="现在最值得做的题组" subtitle="排序综合错题复发、到期复训和当前计划，不再先让你逛题库。"/><div className="divide-y divide-black/[0.045]">{loading?<div className="py-12 text-center text-xs text-[#8a9096]">正在根据错题、复发模式和计划配题…</div>:sets.length===0?<EmptyState title="暂时没有可推荐题组" detail="题库样本不足，先导入一份真实练习，系统再按你的错误模式配题。"/>:sets.map((row,i)=><div key={row.id} className="grid gap-3 py-4 md:grid-cols-[42px_minmax(0,1fr)_auto] md:items-center"><div className="flex h-9 w-9 items-center justify-center rounded-[14px] bg-[linear-gradient(135deg,#e6eeff,#efe8ff)] text-[11px] font-bold text-[#5c66b7]">{String(i+1).padStart(2,'0')}</div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="text-[14px] font-bold text-[#303134]">{row.title}</h3><span className="rounded-full bg-[#f0f2f6] px-2 py-0.5 text-[9px] font-semibold text-[#73787f]">{row.count} 题</span></div><p className="mt-1 text-[11px] leading-5 text-[#7b8087]">{row.reason}</p><div className="mt-1.5 inline-flex items-center gap-1 text-[9px] font-medium text-[#90959b]"><Clock3 className="h-3 w-3"/>约 {row.estimated_minutes} 分钟</div></div><PrimaryButton onClick={()=>start({set_id:row.id,force:false})}><Play className="h-3.5 w-3.5"/>开始</PrimaryButton></div>)}</div></Surface><aside className="space-y-5"><Surface tone="violet" pad="lg"><SectionHeader title="训练规则" action={<Layers3 className="h-4 w-4 text-[#6b5db6]"/>}/><div className="space-y-3 text-[11px] leading-5 text-[#656a70]"><p><b className="text-[#3f4347]">先做推荐：</b>系统已把高复发、高价值和计划相关题放在前面。</p><p><b className="text-[#3f4347]">需要自由选：</b>切到“自选题目”，可按模块和历史对错筛。</p><p><b className="text-[#3f4347]">中断可恢复：</b>题级状态自动保存，重新进入继续当前会话。</p></div></Surface><Surface tone="green" pad="lg"><SectionHeader title="训练存量"/><div className="grid grid-cols-2 gap-3"><div><div className="text-[9px] text-[#8c9298]">题库题目</div><div className="mt-1 text-2xl font-bold">{questions.length}</div></div><div><div className="text-[9px] text-[#8c9298]">历史训练</div><div className="mt-1 text-2xl font-bold">{trainings.length}</div></div></div></Surface></aside></div>}
{tab==='bank'&&<Surface pad="none" className="overflow-hidden"><div className="border-b border-black/[0.05] p-3 md:p-4"><div className="flex flex-wrap items-center gap-2"><div className="relative min-w-[240px] flex-1"><Search className="absolute left-3 top-3 h-3.5 w-3.5 text-[#8d9298]"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索题干、题型或错误模式" className="w-full rounded-2xl bg-[#f4f6fa] py-2.5 pl-9 pr-3 text-xs outline-none ring-1 ring-black/[0.045] focus:bg-white"/></div><select value={module} onChange={e=>setModule(e.target.value)} className="rounded-full bg-[#f4f6fa] px-3 py-2.5 text-[11px] ring-1 ring-black/[0.045]"><option value="all">全部模块</option>{modules.map(m=><option key={m}>{tZen(m,zenMode)}</option>)}</select><select value={correct} onChange={e=>setCorrect(e.target.value as any)} className="rounded-full bg-[#f4f6fa] px-3 py-2.5 text-[11px] ring-1 ring-black/[0.045]"><option value="all">全部历史状态</option><option value="correct">历史正确</option><option value="incorrect">历史错误</option></select><PrimaryButton disabled={!bankIds.length} onClick={()=>{if(!bankIds.length){setError('所选题目缺少题库ID，无法重新训练。');return}start({title:`自选真题 · ${bankIds.length}题`,bank_ids:bankIds,estimated_minutes:Math.max(5,Math.round(bankIds.length*1.5)),force:false})}}>练所选 {bankIds.length} 题</PrimaryButton></div></div><div className="overflow-x-auto"><table className="workspace-data-table w-full min-w-[860px] text-xs"><thead><tr><th className="w-10"></th><th>题型</th><th>题干</th><th>历史状态</th><th>用时</th><th className="text-right">操作</th></tr></thead><tbody>{filtered.map(x=>{const copy=formatQuestionText({id:x.id,module:x.module,subType:x.subType,stem:x.stem,options:x.options});return <tr key={x.id}><td><input type="checkbox" checked={selected.includes(x.id)} disabled={!x.bankId} onChange={()=>toggle(x.id)}/></td><td className="whitespace-nowrap"><b>{tZen(x.module,zenMode)}</b><div className="mt-0.5 text-[9px] text-[#979ca2]">{x.subType}</div></td><td className="max-w-[520px] truncate text-[#51565b]">{x.stem}</td><td>{x.isCorrect===true?<span className="inline-flex items-center gap-1 text-[#34765b]"><CheckCircle2 className="h-3 w-3"/>正确</span>:x.isCorrect===false?<span className="inline-flex items-center gap-1 text-[#a24d68]"><XCircle className="h-3 w-3"/>错误</span>:'—'}</td><td className="font-mono text-[#777c83]">{x.durationSec?`${x.durationSec}s`:'—'}</td><td className="text-right whitespace-nowrap"><CopyButton text={copy} label="复制" className="mr-3"/><button onClick={()=>setSelectedQuestionId(x.id)} className="font-semibold text-[#6571bb]">查看</button></td></tr>})}</tbody></table></div></Surface>}
{tab==='history'&&<Surface pad="none" className="overflow-hidden"><div className="px-5 pt-5"><SectionHeader title="训练记录" subtitle="只看真实训练批次，方便回溯题量、正确率和节奏变化。"/></div><div className="overflow-x-auto"><table className="workspace-data-table w-full min-w-[760px] text-xs"><thead><tr><th>日期</th><th>来源</th><th>题量</th><th>正确率</th><th>总用时</th><th>均速</th><th>备注</th></tr></thead><tbody>{trainings.map(tr=><tr key={tr.id}><td className="font-mono">{tr.date}</td><td>{tr.source}</td><td>{tr.correctQ}/{tr.totalQ}</td><td className="font-mono font-semibold">{Math.round(tr.accuracy*100)}%</td><td>{tr.durationMin}m</td><td>{tr.avgSecPerQ||'—'}s</td><td className="max-w-[360px] truncate text-[#81868d]">{tr.note||'—'}</td></tr>)}</tbody></table></div></Surface>}</WorkspacePage>;
};
