export interface Exam { code:string; name:string; examDate:string; isOfficial:boolean; dateSource?:string; daysLeft:number; paperMinutes:number; totalQuestions:number; totalScore:number; targetScore:number; baselineScore?:number|null; }
export interface PaperModule { id:string; examCode:'guangdong'|'national'|string; name:string; seq:number; questionCount:number; scorePerQ:number; totalScore:number; targetMinutes:number; targetAccuracy:number; currentAccuracy?:number|null; sampleCount:number; avgSeconds?:number|null; trend:number[]; gapText:string; isQualified:boolean; }
export interface PhaseCriterion { id:string; phaseCode:string; label:string; metric:string; scope:string; operator:'gte'|'lte'|'eq'; threshold:number; currentVal:number; passed:boolean; }
export interface Phase { code:string; name:string; seq:number; startWeek:number; endWeek:number; goalMd:string; status:'active'|'pending'|'completed'; criteria:PhaseCriterion[]; }
export interface WeekPlan { weekNo:number; week?:string; startDate:string; endDate:string; theme:string; phase:string; targetHours:number; actualHours:number; targetQuestions:number; actualQuestions:number; moduleHours:Record<string,number>; milestone?:string; completedNodes?:number; targetNodes?:number; }
export type MasteryState='unlearned'|'learning'|'recovered'|'stable'|'mastered';
export interface KnowledgeNode { slug:string; title:string; subject:'xingce'|'shenlun'; module:string; priorityBatch?:number; buildStatus?:string; content:string; charCount?:number; targetSeconds?:number; mastery:MasteryState; sampleN?:number; accuracy?:number|null; }
export interface MethodItem { id:string; label:string; title:string; module:string; definition:string; principle:string; signals:string[]; steps:string[]; example:string; boundary:string; callCommand:string; }
export interface QuestionOption { label:string; text:string; }
export interface Question { id:number; bankId?:number|null; trainingId:string; seq:number; module:string; subType:string; stem:string; options:QuestionOption[]; correctAnswer:string; userChoice?:string; isCorrect?:boolean|null; durationSec?:number|null; explanation:string; errorPattern?:string|null; nodeSlug?:string|null; }
export interface TrainingRecord { id:string; date:string; source:string; totalQ:number; correctQ:number; accuracy:number; durationMin:number; avgSecPerQ:number; note:string; modules:{name:string;total:number;correct:number;accuracy:number}[]; questionIds:number[]; }
export interface MistakeItem { id:number; questionId:number; module:string; stem:string; correctAnswer:string; userChoice:string; errorPattern:string; errorPatternName:string; masteryLevel:number; reviewCount:number; nextReviewDate:string; lastReviewedAt?:string|null; reason:string; aiPrescription:string; status:'pending'|'reviewing'|'fixed'; question?:Question; }
export interface TaskItem { id:string; date:string; priority:'P0'|'P1'|'P2'; title:string; module:string; reason:string; estMinutes:number; steps:string[]; doneCriteria:string; nodeSlugs:string[]; status:'todo'|'done'; actionUrl?:string; }
export interface StudySession { id:string; date:string; startTime:string; durationSec:number; module:string; activityType:string; deepStatus:'deep'|'focus'|'normal'; note:string; }
export interface UserSettings { deepThresholdMin:number; focusThresholdMin:number; weeklyTargetHours:number; targetScores:{guangdong:{xingce:number;shenlun:number};national:{xingce:number;shenlun:number}}; reviewIntervalsDays:number[]; zenMode:boolean; }
