import React,{useEffect,useMemo,useRef,useState} from 'react';
import Markdown from 'react-markdown';
import {Bot,BookMarked,Check,ChevronRight,MessageSquareText,PanelRightClose,Save,Send,Sparkles,Trash2,X} from 'lucide-react';
import {useApp} from '../../context/AppContext';

const OPEN_EVENT='gongkao:open-ai';
const PAGE_TITLES:Record<string,string>={dashboard:'工作台概览',today:'今日任务推进',timer:'专注研习计时',trainings:'训练记录与题库',mistakes:'错题本与缺陷库',review:'错题智能复训',import:'智能练习导入',knowledge:'行测考点知识库',shenlun:'申论规范与语料',methods:'考场方法库',coach:'AI 工作区',weekplan:'周度攻坚日程'};
const CATEGORY_BY_PAGE:Record<string,string>={mistakes:'错题复盘',review:'错题复盘',knowledge:'解题方法',methods:'解题方法',shenlun:'申论表达',today:'训练策略',weekplan:'训练策略',timer:'训练策略',dashboard:'训练策略',trainings:'训练分析',import:'训练分析'};

type Msg={id:string;sender:'user'|'assistant';text:string;time:string;query?:string;pageKey?:string;pageTitle?:string;contextSnapshot?:string;savedId?:number};
type Formula={id:number;title:string;category:string;page_key?:string;page_title?:string;user_query:string;response_md:string;context_snapshot?:string;tags:string[];created_at:string};
const timeNow=()=>new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});
const cleanTitle=(query:string,pageTitle:string)=>`${pageTitle} · ${query.replace(/\s+/g,' ').slice(0,32)}${query.length>32?'…':''}`;

export const GlobalAiDrawer:React.FC=()=>{
  const app=useApp();
  const{activeTab,mistakes,knowledgeNodes,methods,trainings,tasks,sessions}=app;
  const[open,setOpen]=useState(false);const[tab,setTab]=useState<'chat'|'saved'>('chat');const[includePage,setIncludePage]=useState(true);const[input,setInput]=useState('');const[loading,setLoading]=useState(false);const[formulas,setFormulas]=useState<Formula[]>([]);const[saving,setSaving]=useState<string|null>(null);const[expandedFormula,setExpandedFormula]=useState<number|null>(null);
  const[messages,setMessages]=useState<Msg[]>([{id:'welcome',sender:'assistant',text:'我是全局 AI 助手。你可以在任何页面直接提问；勾选“附带当前页面内容”后，我会把当前可见页面作为上下文一起分析。回答默认按固定结构输出，并可一键保存为“定式”。',time:timeNow()}]);
  const endRef=useRef<HTMLDivElement>(null);
  const pageTitle=PAGE_TITLES[activeTab]||'当前页面';
  const currentCategory=CATEGORY_BY_PAGE[activeTab]||'综合定式';

  const summary=useMemo(()=>`工作台全局事实：待复训错题 ${mistakes.filter(m=>m.status!=='fixed').length} 道；知识节点 ${knowledgeNodes.length} 个；正式方法 ${methods.length} 种；训练记录 ${trainings.length} 次；待办任务 ${tasks.filter(t=>t.status!=='done').length} 项；学习记录 ${sessions.length} 条。`,[mistakes,knowledgeNodes,methods,trainings,tasks,sessions]);

  const loadSaved=async()=>{try{const r=await fetch('/api/ai-formulas?limit=200');if(r.ok)setFormulas(await r.json())}catch{}};
  useEffect(()=>{const fn=()=>{setOpen(true);setTab('chat')};window.addEventListener(OPEN_EVENT,fn as EventListener);return()=>window.removeEventListener(OPEN_EVENT,fn as EventListener)},[]);
  useEffect(()=>{if(open)loadSaved()},[open]);
  useEffect(()=>{endRef.current?.scrollIntoView({behavior:'smooth'})},[messages,loading,open]);

  const snapshotPage=()=>{const root=document.getElementById('main-content-area');const raw=(root?.innerText||'').replace(/\n{3,}/g,'\n\n').trim();return raw.slice(0,7000)};
  const send=async()=>{const query=input.trim();if(!query||loading)return;const snapshot=includePage?snapshotPage():'';const context=[`当前页面：${pageTitle}（${activeTab}）`,summary,includePage?`【用户勾选发送的当前页面可见内容】\n${snapshot||'当前页面暂无可见文本。'}`:'用户本轮未勾选发送当前页面内容。'].join('\n\n');const user:Msg={id:`u-${Date.now()}`,sender:'user',text:query,time:timeNow()};const prior=[...messages,user];setMessages(prior);setInput('');setLoading(true);const aid=`a-${Date.now()+1}`;let answer='',started=false;
    try{const res=await fetch('/api/coach/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:prior.filter(m=>m.id!=='welcome').slice(-14).map(m=>({role:m.sender==='user'?'user':'assistant',content:m.text})),context,response_mode:'structured'})});if(!res.ok||!res.body)throw new Error(`HTTP ${res.status}`);const reader=res.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const{done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const chunks=buffer.split('\n\n');buffer=chunks.pop()||'';for(const chunk of chunks){const line=chunk.split('\n').find(x=>x.startsWith('data:'));if(!line)continue;let p:any;try{p=JSON.parse(line.slice(5).trim())}catch{continue}if(p.type==='delta'&&p.text){answer+=p.text;if(!started){started=true;setMessages(prev=>[...prev,{id:aid,sender:'assistant',text:answer,time:timeNow(),query,pageKey:activeTab,pageTitle,contextSnapshot:snapshot}])}else setMessages(prev=>prev.map(m=>m.id===aid?{...m,text:answer}:m))}else if(p.type==='error')throw new Error(p.message||'AI 请求失败')}}if(!started)setMessages(prev=>[...prev,{id:aid,sender:'assistant',text:'本次没有返回正文，请检查 AI 配置后重试。',time:timeNow(),query,pageKey:activeTab,pageTitle,contextSnapshot:snapshot}])}
    catch(e:any){setMessages(prev=>[...prev,{id:aid,sender:'assistant',text:`本次 AI 调用未完成：${e?.message||'未知错误'}\n\n不会生成伪造答案。请检查 DeepSeek 配置或网络。`,time:timeNow(),query,pageKey:activeTab,pageTitle,contextSnapshot:snapshot}])}finally{setLoading(false)}};

  const saveFormula=async(msg:Msg)=>{if(!msg.query||msg.savedId)return;setSaving(msg.id);try{const r=await fetch('/api/ai-formulas',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:cleanTitle(msg.query,msg.pageTitle||pageTitle),category:CATEGORY_BY_PAGE[msg.pageKey||'']||currentCategory,page_key:msg.pageKey,page_title:msg.pageTitle,user_query:msg.query,response_md:msg.text,context_snapshot:msg.contextSnapshot||null,tags:[msg.pageTitle||pageTitle]})});if(!r.ok)throw new Error(`HTTP ${r.status}`);const saved:Formula=await r.json();setMessages(prev=>prev.map(m=>m.id===msg.id?{...m,savedId:saved.id}:m));await loadSaved()}finally{setSaving(null)}};
  const removeFormula=async(id:number)=>{const r=await fetch(`/api/ai-formulas/${id}`,{method:'DELETE'});if(r.ok){setFormulas(prev=>prev.filter(f=>f.id!==id));if(expandedFormula===id)setExpandedFormula(null)}};

  return <>
    {!open&&<button id="global-ai-fab" onClick={()=>setOpen(true)} className="fixed right-5 bottom-5 z-40 px-4 py-3 rounded-2xl bg-stone-900 text-white shadow-xl hover:bg-stone-800 flex items-center gap-2 text-xs font-semibold"><Sparkles className="w-4 h-4 text-amber-400"/><span>问 AI · 本页</span></button>}
    {open&&<div className="fixed inset-0 z-[70] flex justify-end"><div className="absolute inset-0 bg-stone-900/20 backdrop-blur-[1px]" onClick={()=>setOpen(false)}/><section id="global-ai-drawer" className="relative w-full sm:w-[560px] h-full bg-stone-50 border-l border-stone-200 shadow-2xl flex flex-col">
      <div className="px-4 py-3 bg-white border-b border-stone-200 flex items-center justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2"><div className="w-8 h-8 rounded-xl bg-stone-900 text-amber-400 flex items-center justify-center"><Sparkles className="w-4 h-4"/></div><div><h2 className="text-sm font-bold text-stone-900">全局 AI 助手</h2><p className="text-[11px] text-stone-500 truncate">当前：{pageTitle}</p></div></div></div><button onClick={()=>setOpen(false)} className="p-2 rounded-lg text-stone-500 hover:bg-stone-100 hover:text-stone-900"><PanelRightClose className="w-4 h-4"/></button></div>
      <div className="px-4 pt-3 bg-white border-b border-stone-200"><div className="flex items-center gap-1 p-1 rounded-xl bg-stone-100 w-fit"><button onClick={()=>setTab('chat')} className={`px-3 py-1.5 rounded-lg text-xs font-semibold flex items-center gap-1.5 ${tab==='chat'?'bg-white text-stone-900 shadow-sm':'text-stone-600'}`}><MessageSquareText className="w-3.5 h-3.5"/>对话</button><button onClick={()=>{setTab('saved');loadSaved()}} className={`px-3 py-1.5 rounded-lg text-xs font-semibold flex items-center gap-1.5 ${tab==='saved'?'bg-white text-stone-900 shadow-sm':'text-stone-600'}`}><BookMarked className="w-3.5 h-3.5"/>已保存 {formulas.length?`(${formulas.length})`:''}</button></div></div>
      {tab==='chat'?<>
        <div className="flex-1 overflow-y-auto p-4 space-y-4">{messages.map(msg=>{const ai=msg.sender==='assistant';return <div key={msg.id} className={`flex gap-2.5 ${ai?'':'flex-row-reverse'}`}><div className={`w-7 h-7 rounded-full flex-shrink-0 flex items-center justify-center ${ai?'bg-amber-400 text-stone-900':'bg-stone-900 text-white'}`}>{ai?<Bot className="w-3.5 h-3.5"/>:<span className="text-[10px] font-bold">我</span>}</div><div className={`max-w-[88%] ${ai?'':'text-right'}`}><div className={`rounded-2xl px-3.5 py-3 text-xs leading-relaxed ${ai?'bg-white border border-stone-200 text-stone-800 shadow-2xs':'bg-stone-900 text-white'}`}>{ai?<div className="markdown-body prose prose-stone max-w-none text-xs"><Markdown>{msg.text}</Markdown></div>:<div className="whitespace-pre-wrap text-left">{msg.text}</div>}</div><div className={`mt-1.5 flex items-center gap-2 text-[10px] text-stone-400 ${ai?'':'justify-end'}`}><span>{msg.time}</span>{ai&&msg.query&&<button disabled={saving===msg.id||!!msg.savedId} onClick={()=>saveFormula(msg)} className={`inline-flex items-center gap-1 font-medium ${msg.savedId?'text-emerald-600':'text-stone-500 hover:text-stone-900'}`}>{msg.savedId?<><Check className="w-3 h-3"/>已存为定式</>:<><Save className="w-3 h-3"/>{saving===msg.id?'保存中':'保存为定式'}</>}</button>}</div></div></div>})}{loading&&<div className="flex items-center gap-2 text-xs text-stone-500"><span className="w-2 h-2 bg-amber-400 rounded-full animate-pulse"/>AI 正在结合工作台上下文分析...</div>}<div ref={endRef}/></div>
        <div className="p-3 bg-white border-t border-stone-200 space-y-2"><label className="flex items-center justify-between gap-3 px-3 py-2 rounded-xl bg-stone-50 border border-stone-200 cursor-pointer"><div><div className="text-xs font-semibold text-stone-800">附带当前页面内容</div><div className="text-[10px] text-stone-500">勾选后发送当前可见页面文本，最多约 7000 字</div></div><input type="checkbox" checked={includePage} onChange={e=>setIncludePage(e.target.checked)} className="w-4 h-4 accent-stone-900"/></label><div className="flex items-end gap-2 p-2 rounded-2xl border border-stone-300 focus-within:border-stone-500"><textarea rows={3} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder={`针对“${pageTitle}”提问…`} className="flex-1 resize-none border-0 bg-transparent p-1.5 text-xs outline-none"/><button onClick={send} disabled={!input.trim()||loading} className={`p-3 rounded-xl ${input.trim()&&!loading?'bg-stone-900 text-white hover:bg-stone-800':'bg-stone-200 text-stone-400'}`}><Send className="w-4 h-4"/></button></div><div className="text-[10px] text-stone-400 px-1">默认结构化输出：结论 → 条件 → 操作定式 → 边界 → 页面行动 → 依据</div></div>
      </>:<div className="flex-1 overflow-y-auto p-4 space-y-3">{formulas.length===0?<div className="p-8 text-center text-xs text-stone-500">还没有保存的 AI 定式。对话后点击“保存为定式”即可沉淀。</div>:formulas.map(f=><div key={f.id} className="bg-white border border-stone-200 rounded-2xl overflow-hidden"><button onClick={()=>setExpandedFormula(expandedFormula===f.id?null:f.id)} className="w-full p-4 text-left flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2 mb-1"><span className="px-2 py-0.5 rounded-full bg-amber-50 border border-amber-200 text-amber-800 text-[10px] font-semibold">{f.category}</span>{f.page_title&&<span className="text-[10px] text-stone-400">{f.page_title}</span>}</div><div className="text-xs font-bold text-stone-900 truncate">{f.title}</div><div className="text-[10px] text-stone-500 mt-1 truncate">原问题：{f.user_query}</div></div><ChevronRight className={`w-4 h-4 text-stone-400 transition-transform ${expandedFormula===f.id?'rotate-90':''}`}/></button>{expandedFormula===f.id&&<div className="px-4 pb-4 border-t border-stone-100"><div className="markdown-body prose prose-stone max-w-none text-xs pt-3"><Markdown>{f.response_md}</Markdown></div><div className="flex justify-end mt-3"><button onClick={()=>removeFormula(f.id)} className="px-2.5 py-1.5 rounded-lg text-[11px] text-rose-600 hover:bg-rose-50 flex items-center gap-1"><Trash2 className="w-3 h-3"/>删除定式</button></div></div>}</div>)}</div>}
    </section></div>}
  </>;
};
