import React from 'react';

type Tone='plain'|'blue'|'violet'|'warm'|'green'|'rose'|'ink';

const toneStyle:Record<Tone,React.CSSProperties>={
  plain:{background:'var(--wb-surface)',color:'var(--wb-text)',borderColor:'var(--wb-border)'},
  blue:{background:'color-mix(in srgb, var(--wb-accent-soft) 72%, var(--wb-surface))',color:'var(--wb-text)',borderColor:'color-mix(in srgb, var(--wb-accent) 24%, var(--wb-border))'},
  violet:{background:'color-mix(in srgb, var(--wb-purple-soft) 60%, var(--wb-surface))',color:'var(--wb-text)',borderColor:'color-mix(in srgb, var(--wb-purple) 20%, var(--wb-border))'},
  warm:{background:'color-mix(in srgb, var(--wb-warning-soft) 70%, var(--wb-surface))',color:'var(--wb-text)',borderColor:'color-mix(in srgb, var(--wb-warning) 20%, var(--wb-border))'},
  green:{background:'color-mix(in srgb, var(--wb-success-soft) 70%, var(--wb-surface))',color:'var(--wb-text)',borderColor:'color-mix(in srgb, var(--wb-success) 20%, var(--wb-border))'},
  rose:{background:'color-mix(in srgb, var(--wb-danger-soft) 70%, var(--wb-surface))',color:'var(--wb-text)',borderColor:'color-mix(in srgb, var(--wb-danger) 18%, var(--wb-border))'},
  ink:{background:'var(--wb-text)',color:'var(--wb-surface)',borderColor:'var(--wb-text)'},
};

export const WorkspacePage:React.FC<{children:React.ReactNode;className?:string;id?:string}>=({children,className='',id})=><div id={id} className={`workspace-page relative w-full px-[clamp(16px,1.65vw,28px)] py-[clamp(16px,1.8vw,28px)] ${className}`}>{children}</div>;

export const PageHeader:React.FC<{eyebrow?:React.ReactNode;title:React.ReactNode;subtitle?:React.ReactNode;actions?:React.ReactNode;compact?:boolean}>=({eyebrow,title,subtitle,actions,compact=false})=><header className={`workspace-page-header flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between ${compact?'mb-4':'mb-6'}`}><div className="min-w-0"><div className="mb-1 text-[11px] font-semibold tracking-[0.08em] uppercase" style={{color:'var(--wb-text-3)'}}>{eyebrow}</div><h1 className={`${compact?'text-[22px]':'text-[26px] md:text-[30px]'} font-semibold leading-tight tracking-[-0.03em]`} style={{color:'var(--wb-text)'}}>{title}</h1>{subtitle&&<div className="mt-2 max-w-[900px] text-[13px] leading-6" style={{color:'var(--wb-text-2)'}}>{subtitle}</div>}</div>{actions&&<div className="flex flex-wrap items-center gap-2 lg:justify-end">{actions}</div>}</header>;

export const Surface:React.FC<{children:React.ReactNode;className?:string;tone?:Tone;pad?:'none'|'sm'|'md'|'lg';as?:'div'|'section'|'article';interactive?:boolean}>=({children,className='',tone='plain',pad='md',as='section',interactive=false})=>{const Tag=as as any;const pads={none:'',sm:'p-3 md:p-3.5',md:'p-4 md:p-5',lg:'p-5 md:p-6'};return <Tag data-interactive={interactive?'true':undefined} style={toneStyle[tone]} className={`workspace-surface rounded-[10px] border ${pads[pad]} ${className}`}>{children}</Tag>};

export const HeroPanel:React.FC<{children:React.ReactNode;className?:string;tone?:Tone}>=({children,className='',tone='plain'})=><Surface as="section" tone={tone} pad="none" className={`overflow-hidden ${className}`}><div className="p-5 md:p-6 lg:p-7">{children}</div></Surface>;

export const SectionHeader:React.FC<{title:React.ReactNode;subtitle?:React.ReactNode;action?:React.ReactNode;eyebrow?:React.ReactNode}>=({title,subtitle,action,eyebrow})=><div className="mb-4 flex items-start justify-between gap-4"><div className="min-w-0">{eyebrow&&<div className="mb-1 text-[10px] font-semibold tracking-[0.08em] uppercase" style={{color:'var(--wb-text-3)'}}>{eyebrow}</div>}<h2 className="text-[14px] font-semibold tracking-[-0.01em]" style={{color:'var(--wb-text)'}}>{title}</h2>{subtitle&&<div className="mt-1 text-[12px] leading-5" style={{color:'var(--wb-text-2)'}}>{subtitle}</div>}</div>{action&&<div className="flex-shrink-0">{action}</div>}</div>;

export const Metric:React.FC<{label:React.ReactNode;value:React.ReactNode;note?:React.ReactNode;icon?:React.ReactNode;accent?:string;compact?:boolean}>=({label,value,note,icon,accent='',compact=false})=><div className={`min-w-0 ${compact?'py-1':'py-2'}`}><div className="flex items-center gap-1.5 text-[11px] font-medium" style={{color:'var(--wb-text-2)'}}>{icon}{label}</div><div className={`${compact?'mt-1 text-xl':'mt-1.5 text-2xl'} font-semibold tracking-[-0.035em] ${accent}`} style={accent?undefined:{color:'var(--wb-text)'}}>{value}</div>{note&&<div className="mt-1 text-[11px] leading-4" style={{color:'var(--wb-text-3)'}}>{note}</div>}</div>;

export const MetricRail:React.FC<{children:React.ReactNode;className?:string;columns?:string}>=({children,className='',columns='grid-cols-2 lg:grid-cols-4'})=><div className={`grid ${columns} gap-x-5 gap-y-3 ${className}`}>{React.Children.map(children,(child,i)=><div className={`${i?'sm:border-l sm:pl-5':''}`} style={{borderColor:'var(--wb-border)'}}>{child}</div>)}</div>;

export const Segmented:React.FC<{items:Array<{id:string;label:React.ReactNode}>;value:string;onChange:(id:any)=>void;className?:string}>=({items,value,onChange,className=''})=><div className={`inline-flex items-center rounded-[8px] p-1 ${className}`} style={{background:'var(--wb-surface-subtle)',border:'1px solid var(--wb-border)'}}>{items.map(item=><button key={item.id} onClick={()=>onChange(item.id)} className="rounded-[6px] px-3 py-1.5 text-[12px] font-medium transition-[background-color,color,box-shadow]" style={value===item.id?{background:'var(--wb-surface)',color:'var(--wb-text)',boxShadow:'var(--wb-shadow-sm)'}:{color:'var(--wb-text-2)'}}>{item.label}</button>)}</div>;

export const Toolbar:React.FC<{children:React.ReactNode;className?:string}>=({children,className=''})=><div className={`workspace-toolbar flex flex-wrap items-center gap-2 rounded-[10px] border p-2 ${className}`}>{children}</div>;

export const PrimaryButton:React.FC<React.ButtonHTMLAttributes<HTMLButtonElement> & {soft?:boolean}>=({children,className='',soft=false,...props})=><button {...props} className={`wb-focus-ring inline-flex items-center justify-center gap-1.5 rounded-[8px] px-3.5 py-2 text-[12px] font-semibold transition-[background-color,color,border-color,transform] active:translate-y-px disabled:cursor-not-allowed disabled:opacity-45 ${className}`} style={soft?{background:'var(--wb-accent-soft)',color:'var(--wb-accent-text)',border:'1px solid color-mix(in srgb, var(--wb-accent) 22%, var(--wb-border))'}:{background:'var(--wb-accent)',color:'#fff',border:'1px solid var(--wb-accent)'}}>{children}</button>;

export const QuietButton:React.FC<React.ButtonHTMLAttributes<HTMLButtonElement>>=({children,className='',...props})=><button {...props} className={`wb-focus-ring inline-flex items-center justify-center gap-1.5 rounded-[8px] border px-3 py-2 text-[12px] font-medium transition-[background-color,color,border-color] ${className}`} style={{background:'var(--wb-surface)',color:'var(--wb-text-2)',borderColor:'var(--wb-border)'}}>{children}</button>;

export const EmptyState:React.FC<{title:React.ReactNode;detail?:React.ReactNode;action?:React.ReactNode}>=({title,detail,action})=><div className="flex min-h-[180px] flex-col items-center justify-center rounded-[10px] border px-6 py-10 text-center" style={{background:'var(--wb-surface)',borderColor:'var(--wb-border)'}}><div className="text-sm font-semibold" style={{color:'var(--wb-text)'}}>{title}</div>{detail&&<div className="mt-1.5 max-w-lg text-[12px] leading-5" style={{color:'var(--wb-text-2)'}}>{detail}</div>}{action&&<div className="mt-4">{action}</div>}</div>;
