import React,{useMemo,useState} from 'react';
import {Calendar,Eye,EyeOff,HelpCircle,Menu,Pause,Play,Sparkles,Square,Timer} from 'lucide-react';
import {useApp} from '../../context/AppContext';
import {tZen} from '../../utils/zen';

const fmt=(sec:number)=>{const m=Math.floor(sec/60),s=sec%60;return `${m.toString().padStart(2,'0')}:${s.toString().padStart(2,'0')}`};
const localDate=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const durationLabel=(sec:number)=>sec<3600?`${Math.round(sec/60)} 分钟`:`${(sec/3600).toFixed(1)} 小时`;

export const Header:React.FC<{onOpenShortcuts:()=>void;onOpenSidebar?:()=>void}>=({onOpenShortcuts,onOpenSidebar})=>{
  const{exams,timerState,startTimer,pauseTimer,resumeTimer,stopTimer,sessions,setActiveTab,zenMode,toggleZenMode}=useApp();
  const[gd,national]=exams;const[showTimer,setShowTimer]=useState(false);
  const stats=useMemo(()=>{const now=new Date();const today=localDate(now);const day=(now.getDay()+6)%7;const monday=new Date(now);monday.setDate(now.getDate()-day);const weekStart=localDate(monday);return{todaySec:sessions.filter(s=>s.date===today).reduce((a,s)=>a+Number(s.durationSec||0),0),weekSec:sessions.filter(s=>s.date>=weekStart&&s.date<=today).reduce((a,s)=>a+Number(s.durationSec||0),0)}},[sessions]);
  const toggleTimer=async()=>{if(timerState.status==='idle')await startTimer();else if(timerState.status==='running')await pauseTimer();else await resumeTimer()};
  const openAi=()=>window.dispatchEvent(new CustomEvent('gongkao:open-ai'));
  return <header id="app-header" className="h-16 bg-white border-b border-stone-200/90 px-4 md:px-6 flex items-center justify-between sticky top-0 z-30 select-none shadow-[0_1px_3px_rgba(0,0,0,0.02)]">
    <div className="flex items-center gap-3 md:gap-5">{onOpenSidebar&&<button onClick={onOpenSidebar} className="md:hidden p-2 -ml-1 text-stone-600 hover:text-stone-900 rounded-lg hover:bg-stone-100"><Menu className="w-5 h-5"/></button>}<button onClick={()=>setActiveTab('dashboard')} className="flex items-center gap-2.5 group text-left"><div className="w-8 h-8 rounded-lg bg-stone-900 text-white flex items-center justify-center font-bold text-sm tracking-tight transition-transform group-hover:scale-105">27</div><div><h1 className="font-semibold text-stone-900 text-sm md:text-base leading-tight tracking-tight">{tZen('2027 公考备考工作台',zenMode)}</h1><p className="text-[11px] text-stone-600 font-mono hidden sm:block">{zenMode?'Workstation & Personal Knowledge':'Guangdong & National Civil Service Track'}</p></div></button><div className="hidden lg:flex items-center gap-2 text-xs">{gd&&<div className="px-2.5 py-1 rounded-full bg-amber-50/80 border border-amber-200/70 text-amber-900 flex items-center gap-1.5 font-medium"><Calendar className="w-3 h-3 text-amber-600"/><span>{tZen('广东省考',zenMode)}</span><b className="font-mono">{gd.daysLeft}</b><span className="text-[11px]">天</span></div>}{national&&<div className="px-2.5 py-1 rounded-full bg-blue-50/80 border border-blue-200/70 text-blue-900 flex items-center gap-1.5 font-medium"><Calendar className="w-3 h-3 text-blue-600"/><span>{tZen('国考副省级',zenMode)}</span><b className="font-mono">{national.daysLeft}</b><span className="text-[11px]">天</span></div>}</div></div>
    <div className="flex items-center gap-2 md:gap-3"><div className="relative">{timerState.status!=='idle'?<button id="btn-compact-timer" onClick={()=>setShowTimer(v=>!v)} className={`flex items-center gap-2 px-3 py-1.5 rounded-lg border text-xs font-mono transition-all ${timerState.status==='running'?'bg-emerald-50 border-emerald-300 text-emerald-800 shadow-sm':'bg-amber-50 border-amber-300 text-amber-800'}`}><span className={`w-2 h-2 rounded-full ${timerState.status==='running'?'bg-emerald-600':'bg-amber-500'}`}/><b>{fmt(timerState.elapsedSec)}</b><span className="hidden sm:inline text-stone-600">[{timerState.currentModule}]</span></button>:<button id="btn-compact-timer" onClick={()=>setShowTimer(v=>!v)} className="p-2 rounded-lg text-stone-600 hover:text-stone-900 hover:bg-stone-100 border border-transparent" title="专注计时"><Timer className="w-4 h-4"/></button>}{showTimer&&<div id="compact-timer-popover" className="absolute right-0 top-11 w-64 rounded-2xl bg-white border border-stone-200 shadow-xl p-4 z-50"><div className="flex items-center justify-between"><div><div className="text-[10px] text-stone-500">专注计时</div><div className="text-xl font-bold font-mono mt-0.5">{fmt(timerState.elapsedSec)}</div></div><span className="text-[10px] text-stone-500">{timerState.currentModule}</span></div><div className="grid grid-cols-2 gap-2 mt-3 text-xs"><div className="rounded-lg bg-stone-50 border border-stone-200 p-2"><div className="text-[10px] text-stone-500">今日累计</div><b>{durationLabel(stats.todaySec)}</b></div><div className="rounded-lg bg-stone-50 border border-stone-200 p-2"><div className="text-[10px] text-stone-500">本周累计</div><b>{durationLabel(stats.weekSec)}</b></div></div><div className="flex gap-2 mt-3"><button onClick={()=>void toggleTimer()} className="flex-1 px-3 py-2 rounded-lg bg-stone-900 text-white text-xs font-semibold flex items-center justify-center gap-1.5">{timerState.status==='running'?<><Pause className="w-3.5 h-3.5"/>暂停</>:<><Play className="w-3.5 h-3.5"/>{timerState.status==='paused'?'继续':'开始'}</>}</button>{timerState.status!=='idle'&&<button onClick={async()=>{await stopTimer();setShowTimer(false)}} className="px-3 py-2 rounded-lg border border-stone-200 text-stone-700 text-xs flex items-center gap-1"><Square className="w-3 h-3"/>结束</button>}</div></div>}</div>
      <button id="btn-zen-mode" onClick={toggleZenMode} className={`px-2.5 py-1.5 rounded-lg text-xs font-medium flex items-center gap-1.5 border transition-colors ${zenMode?'bg-emerald-50 text-emerald-800 border-emerald-300 shadow-xs':'bg-stone-50 text-stone-600 border-stone-200 hover:text-stone-900 hover:bg-stone-100'}`}>{zenMode?<><EyeOff className="w-3.5 h-3.5 text-emerald-600"/><span className="hidden sm:inline">隐蔽中</span></>:<><Eye className="w-3.5 h-3.5"/><span className="hidden sm:inline">隐蔽 (Alt+Z)</span></>}</button>
      <button id="btn-header-coach" onClick={openAi} className="px-2.5 py-1.5 rounded-lg text-xs font-medium flex items-center gap-1.5 text-indigo-700 bg-indigo-50/80 hover:bg-indigo-100 border border-indigo-200/80"><Sparkles className="w-3.5 h-3.5 text-indigo-600"/><span className="hidden sm:inline">{tZen('AI 助手',zenMode)}</span></button><button id="btn-shortcuts" onClick={onOpenShortcuts} className="p-2 rounded-lg text-stone-600 hover:text-stone-800 hover:bg-stone-100"><HelpCircle className="w-4 h-4"/></button>
    </div>
  </header>;
};
